#Reading Data and Creating Dataframes city wise

In [4]:
import os
import pandas as pd
from pathlib import Path
data_dir = Path.cwd().parent/'datapack'
os.listdir(data_dir)

['bookings',
 'campaigns',
 'collections',
 'invoices',
 'MANIFEST.json',
 'patients',
 'payments',
 'plan',
 'README.md',
 'reference',
 'results']

In [2]:
for item in data_dir.iterdir():
    print(item.name, "(folder)" if item.is_dir() else "(file)")

bookings (folder)
campaigns (folder)
collections (folder)
invoices (folder)
MANIFEST.json (file)
patients (folder)
payments (folder)
plan (folder)
README.md (file)
reference (folder)
results (folder)

##Booking

In [3]:
booking_path = data_dir /'bookings'

###Legacy

In [4]:
def read_city_csv_legacy(city_path):
    df_list = []

    for item in city_path.iterdir():
        item_path = city_path /item.name 
        #print(item_path)
        df = pd.read_csv(item_path, compression="gzip", encoding="latin-1")
        df_list.append(df)

    return pd.concat(df_list, ignore_index=True)

####Ahmedabad

In [5]:
ahmd_path = booking_path / 'legacy' / 'ahmedabad'
df_ahmed = read_city_csv_legacy(ahmd_path)
df_ahmed.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-AHM-202501-000001,08/01/2025 03:16,09/01/2025 08:26,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T009,800,0
1,BK-AHM-202501-000001,08/01/2025 03:16,09/01/2025 08:26,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T004,650,0
2,BK-AHM-202501-000001,08/01/2025 03:16,09/01/2025 08:26,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T007,550,0
3,BK-AHM-202501-000002,03/01/2025 05:18,06/01/2025 13:22,Ahmedabad,AHM-04,clinic,app,PAHM0031384,Nisha Iyer,T004,650,0
4,BK-AHM-202501-000003,27/01/2025 10:46,28/01/2025 13:37,Ahmedabad,AHM-01,home,app,PAHM0027001,Sneha Menon,T003,450,150

####Bengaluru

In [6]:
beng_path = booking_path / 'legacy' / 'bengaluru'
df_beng = read_city_csv_legacy(beng_path)
df_beng.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-BLR-202501-000001,09/01/2025 07:04,09/01/2025 13:36,Bangalore,BLR-05,clinic,app,PBLR0020199,Manish Pillai,T010,150,0
1,BK-BLR-202501-000001,09/01/2025 07:04,09/01/2025 13:36,Bangalore,BLR-05,clinic,app,PBLR0020199,Manish Pillai,T016,160,0
2,BK-BLR-202501-000001,09/01/2025 07:04,09/01/2025 13:36,Bangalore,BLR-05,clinic,app,PBLR0020199,Manish Pillai,T003,450,0
3,BK-BLR-202501-000002,18/01/2025 07:25,22/01/2025 08:15,Bangalore,BLR-05,home,app,PBLR0024020,Manish Menon,PK01,1499,150
4,BK-BLR-202501-000002,18/01/2025 07:25,22/01/2025 08:15,Bangalore,BLR-05,home,app,PBLR0024020,Manish Menon,T010,150,150

####Chennai

In [7]:
chen_path = booking_path / 'legacy' / 'chennai'
df_chen = read_city_csv_legacy(chen_path)
df_chen.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-CHE-202501-000001,18/01/2025 09:56,23/01/2025 12:44,Chennai,CHE-01,home,app,PCHE0034759,Pooja Mehta,T002,120,150
1,BK-CHE-202501-000002,04/01/2025 00:20,09/01/2025 08:52,Chennai,CHE-01,clinic,app,PCHE0018901,Manish Reddy,T014,150,0
2,BK-CHE-202501-000002,04/01/2025 00:20,09/01/2025 08:52,Chennai,CHE-01,clinic,app,PCHE0018901,Manish Reddy,T001,350,0
3,BK-CHE-202501-000003,24/01/2025 05:48,29/01/2025 09:24,Chennai,CHE-01,home,app,PCHE0032062,Saanvi Desai,T006,650,150
4,BK-CHE-202501-000004,18/01/2025 17:17,21/01/2025 19:29,Chennai,CHE-04,home,app,PCHE0031311,Farhan Reddy,T006,650,150

####Hyderabad

In [8]:
hyd_path = booking_path / 'legacy' / 'hyderabad'
df_hyd = read_city_csv_legacy(hyd_path)
df_hyd.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-HYD-202501-000001,02/01/2025 01:31,06/01/2025 10:20,Hyderabad,HYD-01,home,app,PHYD0030014,Pooja D'Souza,T014,150,150
1,BK-HYD-202501-000002,18/01/2025 02:44,19/01/2025 07:27,Hyderabad,HYD-01,home,app,PHYD0028402,José Iyer,PK01,1499,150
2,BK-HYD-202501-000002,18/01/2025 02:44,19/01/2025 07:27,Hyderabad,HYD-01,home,app,PHYD0028402,José Iyer,T002,120,150
3,BK-HYD-202501-000003,20/01/2025 03:22,25/01/2025 06:19,Hyderabad,HYD-01,home,walkin,PHYD0004237,Priya Bose,T008,1100,150
4,BK-HYD-202501-000003,20/01/2025 03:22,25/01/2025 06:19,Hyderabad,HYD-01,home,walkin,PHYD0004237,Priya Bose,T010,150,150

####Jaipur

In [9]:
jai_path = booking_path / 'legacy' / 'jaipur'
df_jai = read_city_csv_legacy(jai_path)
df_jai.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-JAI-202501-000001,31/12/2024 16:55,01/01/2025 18:14,Jaipur,JAI-01,home,app,PJAI0011173,Rahul Pillai,T013,400,150
1,BK-JAI-202501-000002,14/01/2025 03:12,18/01/2025 08:36,Jaipur,JAI-01,clinic,app,PJAI0008991,Manish Sharma,T002,120,0
2,BK-JAI-202501-000002,14/01/2025 03:12,18/01/2025 08:36,Jaipur,JAI-01,clinic,app,PJAI0008991,Manish Sharma,T007,550,0
3,BK-JAI-202501-000003,30/12/2024 05:11,01/01/2025 10:42,Jaipur,JAI-03,clinic,app,PJAI0013991,Zoya Mehta,T013,400,0
4,BK-JAI-202501-000003,30/12/2024 05:11,01/01/2025 10:42,Jaipur,JAI-03,clinic,app,PJAI0013991,Zoya Mehta,T007,550,0

####Pune

In [10]:
pun_path = booking_path / 'legacy' / 'pune'
df_pun = read_city_csv_legacy(pun_path)
df_pun.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-PUN-202501-000001,16/01/2025 02:47,21/01/2025 10:06,Pune,PUN-01,clinic,phone,PPUN0004761,Mary Reddy,T003,450,0
1,BK-PUN-202501-000001,16/01/2025 02:47,21/01/2025 10:06,Pune,PUN-01,clinic,phone,PPUN0004761,Mary Reddy,T009,800,0
2,BK-PUN-202501-000001,16/01/2025 02:47,21/01/2025 10:06,Pune,PUN-01,clinic,phone,PPUN0004761,Mary Reddy,T013,400,0
3,BK-PUN-202501-000002,27/01/2025 11:21,27/01/2025 18:08,Pune,PUN-02,home,phone,PPUN0013160,Aditi Kulkarni,T011,750,150
4,BK-PUN-202501-000003,24/01/2025 06:18,26/01/2025 07:45,Pune,PUN-05,clinic,app,PPUN0021383,Saanvi Desai,T004,650,0

###Nova

In [11]:
file_path = booking_path /'nova' /'chennai'/'bookings_2026-04.jsonl.gz'

df = pd.read_json(file_path, lines=True, compression="gzip")
print(df.shape)
df.head()

(5903, 12)

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,"{'patient_id': 'PCHE0044922', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,NaN,booked
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'patient_id': 'PCHE0047035', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T01...",0,NaN,booked
2,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,"{'patient_id': 'PCHE0051652', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T00...",0,NaN,booked
3,nova_che_0087559,2026-04-16 05:53:00+05:30,2026-04-21 08:08:00+05:30,Chennai,CHE-02,HOME,APP,"{'patient_id': 'PCHE0040733', 'is_new': False}","[{'code': 'T006', 'price': 650}, {'code': 'T00...",150,NaN,booked
4,nova_che_0087560,2026-04-07 05:57:00+05:30,2026-04-08 08:46:00+05:30,Chennai,CHE-05,CLINIC,WALKIN,"{'patient_id': 'PCHE0037380', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,NaN,rescheduled

In [12]:
df_chen.info()

<class 'pandas.DataFrame'>
RangeIndex: 202121 entries, 0 to 202120
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   booking_id    202121 non-null  str
 1   created_at    202121 non-null  str
 2   slot_at       202121 non-null  str
 3   city          202121 non-null  str
 4   clinic_id     202121 non-null  str
 5   channel       202121 non-null  str
 6   source        202121 non-null  str
 7   patient_id    202121 non-null  str
 8   patient_name  202121 non-null  str
 9   test_code     201929 non-null  str
 10  test_price    202121 non-null  object
 11  home_fee      202121 non-null  object
dtypes: object(2), str(10)
memory usage: 18.5+ MB

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5903 entries, 0 to 5902
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        5903 non-null   str
 1   created_at        5903 non-null   datetime64[us, UTC+05:30]
 2   slot_at           5903 non-null   datetime64[us, UTC+05:30]
 3   city              5903 non-null   str
 4   clinic_id         5903 non-null   str
 5   channel           5903 non-null   str
 6   source            5903 non-null   str
 7   patient           5903 non-null   object
 8   tests             5903 non-null   object
 9   home_fee          5903 non-null   int64
 10  rescheduled_from  334 non-null    str
 11  status_at_export  5903 non-null   str
dtypes: datetime64[us, UTC+05:30](2), int64(1), object(2), str(7)
memory usage: 553.5+ KB

In [14]:
patient_df = pd.json_normalize(df['patient'])
patient_df.head()

    patient_id  is_new
0  PCHE0044922   False
1  PCHE0047035   False
2  PCHE0051652   False
3  PCHE0040733   False
4  PCHE0037380   False

In [15]:
df_new = pd.concat( [df.drop(columns=['patient']), patient_df], axis=1 )
df_new.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,"[{'code': 'T007', 'price': 550}]",0,NaN,booked,PCHE0044922,False
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"[{'code': 'T007', 'price': 550}, {'code': 'T01...",0,NaN,booked,PCHE0047035,False
2,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,"[{'code': 'T004', 'price': 650}, {'code': 'T00...",0,NaN,booked,PCHE0051652,False
3,nova_che_0087559,2026-04-16 05:53:00+05:30,2026-04-21 08:08:00+05:30,Chennai,CHE-02,HOME,APP,"[{'code': 'T006', 'price': 650}, {'code': 'T00...",150,NaN,booked,PCHE0040733,False
4,nova_che_0087560,2026-04-07 05:57:00+05:30,2026-04-08 08:46:00+05:30,Chennai,CHE-05,CLINIC,WALKIN,"[{'code': 'T007', 'price': 550}]",0,NaN,rescheduled,PCHE0037380,False

In [16]:
df_new = df_new.explode('tests', ignore_index=True)
df_new.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,"{'code': 'T007', 'price': 550}",0,NaN,booked,PCHE0044922,False
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'code': 'T007', 'price': 550}",0,NaN,booked,PCHE0047035,False
2,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'code': 'T011', 'price': 750}",0,NaN,booked,PCHE0047035,False
3,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'code': 'T004', 'price': 650}",0,NaN,booked,PCHE0047035,False
4,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,"{'code': 'T004', 'price': 650}",0,NaN,booked,PCHE0051652,False

In [17]:
tests_df = pd.json_normalize(df_new['tests'])
tests_df = tests_df.add_prefix('test_')
tests_df.head()

  test_code  test_price
0      T007       550.0
1      T007       550.0
2      T011       750.0
3      T004       650.0
4      T004       650.0

In [18]:
df_new = pd.concat([df_new.drop(columns=['tests']), tests_df], axis=1)
df_new.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,0,NaN,booked,PCHE0044922,False,T007,550.0
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T007,550.0
2,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T011,750.0
3,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T004,650.0
4,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,0,NaN,booked,PCHE0051652,False,T004,650.0

In [19]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 13821 entries, 0 to 13820
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        13821 non-null  str
 1   created_at        13821 non-null  datetime64[us, UTC+05:30]
 2   slot_at           13821 non-null  datetime64[us, UTC+05:30]
 3   city              13821 non-null  str
 4   clinic_id         13821 non-null  str
 5   channel           13821 non-null  str
 6   source            13821 non-null  str
 7   home_fee          13821 non-null  int64
 8   rescheduled_from  763 non-null    str
 9   status_at_export  13821 non-null  str
 10  patient_id        13821 non-null  str
 11  is_new            13821 non-null  bool
 12  test_code         13816 non-null  str
 13  test_price        13816 non-null  float64
dtypes: bool(1), datetime64[us, UTC+05:30](2), float64(1), int64(1), str(9)
memory usage: 1.4 MB

In [20]:
df_new.shape[0]

13821

In [21]:
df_new.loc[df_new['is_new']]

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
11056,nova_che_0092290,2026-04-14 22:09:00+05:30,2026-04-17 06:49:00+05:30,Chennai,CHE-01,CLINIC,APP,0,NaN,booked,PCHE0052623,True,T001,350.0
11057,nova_che_0092290,2026-04-14 22:09:00+05:30,2026-04-17 06:49:00+05:30,Chennai,CHE-01,CLINIC,APP,0,NaN,booked,PCHE0052623,True,PK01,1499.0
11058,nova_che_0092290,2026-04-14 22:09:00+05:30,2026-04-17 06:49:00+05:30,Chennai,CHE-01,CLINIC,APP,0,NaN,booked,PCHE0052623,True,T004,650.0
11059,nova_che_0092291,2026-04-15 07:51:00+05:30,2026-04-15 16:10:00+05:30,Chennai,CHE-01,HOME,APP,150,NaN,booked,PCHE0052624,True,T010,150.0
11060,nova_che_0092291,2026-04-15 07:51:00+05:30,2026-04-15 16:10:00+05:30,Chennai,CHE-01,HOME,APP,150,NaN,booked,PCHE0052624,True,T009,800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13775,nova_che_0093436,2026-04-04 01:49:00+05:30,2026-04-13 06:35:00+05:30,Chennai,CHE-02,CLINIC,APP,0,nova_che_0092862,booked,PCHE0053195,True,T009,800.0
13776,nova_che_0093436,2026-04-04 01:49:00+05:30,2026-04-13 06:35:00+05:30,Chennai,CHE-02,CLINIC,APP,0,nova_che_0092862,booked,PCHE0053195,True,T011,750.0
13777,nova_che_0093436,2026-04-04 01:49:00+05:30,2026-04-13 06:35:00+05:30,Chennai,CHE-02,CLINIC,APP,0,nova_che_0092862,booked,PCHE0053195,True,T010,150.0
13792,nova_che_0093445,2026-04-15 07:24:00+05:30,2026-04-19 16:57:00+05:30,Chennai,CHE-02,HOME,APP,150,nova_che_0092441,booked,PCHE0052774,True,PK02,2999.0
13818,nova_che_0093456,2026-04-24 09:35:00+05:30,2026-04-27 11:18:00+05:30,Chennai,CHE-02,HOME,APP,150,nova_che_0092296,booked,PCHE0052629,True,T001,350.0

In [22]:
def read_json_nova(city_path):
    df_list = []

    for item in city_path.iterdir():
        item_path = city_path /item.name 
        df = pd.read_json(item_path, lines=True, compression="gzip")
        patient_df = pd.json_normalize(df['patient'])
        df = pd.concat( [df.drop(columns=['patient']), patient_df], axis=1 )
        df = df.explode('tests', ignore_index=True)
        tests_df = pd.json_normalize(df['tests'])
        tests_df = tests_df.add_prefix('test_')
        df = pd.concat([df.drop(columns=['tests']), tests_df], axis=1)
        df_list.append(df)

    return pd.concat(df_list, ignore_index=True)

####Chennai

In [23]:
chen_nova_path = booking_path /'nova' /'chennai'

df_chen_nova = read_json_nova(chen_nova_path)
df_chen_nova

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,0,NaN,booked,PCHE0044922,False,T007,550.0
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T007,550.0
2,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T011,750.0
3,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T004,650.0
4,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,0,NaN,booked,PCHE0051652,False,T004,650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41424,nova_che_0105175,2026-06-20 23:53:00+05:30,2026-06-25 06:47:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,nova_che_0102557,booked,PCHE0051878,False,T001,350.0
41425,nova_che_0105175,2026-06-20 23:53:00+05:30,2026-06-25 06:47:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,nova_che_0102557,booked,PCHE0051878,False,T013,400.0
41426,nova_che_0105175,2026-06-20 23:53:00+05:30,2026-06-25 06:47:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,nova_che_0102557,booked,PCHE0051878,False,T017,450.0
41427,nova_che_0105176,2026-06-04 10:33:00+05:30,2026-06-08 19:28:00+05:30,Chennai,CHE-05,CLINIC,APP,0,nova_che_0100657,booked,PCHE0052069,False,T005,700.0
41428,nova_che_0105176,2026-06-04 10:33:00+05:30,2026-06-08 19:28:00+05:30,Chennai,CHE-05,CLINIC,APP,0,nova_che_0100657,booked,PCHE0052069,False,T001,350.0

####Jaipur

In [24]:
jai_nova_path = booking_path /'nova' /'jaipur'

df_jai_nova = read_json_nova(jai_nova_path)
df_jai_nova

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_jai_0046832,2026-04-26 05:50:00+05:30,2026-04-27 06:29:00+05:30,Jaipur,JAI-01,CLINIC,WALKIN,0,NaN,booked,PJAI0027168,False,PK04,2499.0
1,nova_jai_0046832,2026-04-26 05:50:00+05:30,2026-04-27 06:29:00+05:30,Jaipur,JAI-01,CLINIC,WALKIN,0,NaN,booked,PJAI0027168,False,T008,1100.0
2,nova_jai_0046832,2026-04-26 05:50:00+05:30,2026-04-27 06:29:00+05:30,Jaipur,JAI-01,CLINIC,WALKIN,0,NaN,booked,PJAI0027168,False,T007,550.0
3,nova_jai_0046832,2026-04-26 05:50:00+05:30,2026-04-27 06:29:00+05:30,Jaipur,JAI-01,CLINIC,WALKIN,0,NaN,booked,PJAI0027168,False,T018,700.0
4,nova_jai_0046833,2026-03-30 13:38:00+05:30,2026-04-02 18:44:00+05:30,Jaipur,JAI-02,HOME,APP,150,NaN,booked,PJAI0020207,False,T007,550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21005,nova_jai_0055752,2026-06-07 02:29:00+05:30,2026-06-12 11:18:00+05:30,Jaipur,JAI-02,HOME,PHONE,150,nova_jai_0052790,booked,PJAI0017296,False,T007,550.0
21006,nova_jai_0055752,2026-06-07 02:29:00+05:30,2026-06-12 11:18:00+05:30,Jaipur,JAI-02,HOME,PHONE,150,nova_jai_0052790,booked,PJAI0017296,False,T006,650.0
21007,nova_jai_0055753,2026-06-05 07:51:00+05:30,2026-06-06 10:25:00+05:30,Jaipur,JAI-03,CLINIC,PHONE,0,nova_jai_0054062,booked,PJAI0027566,False,T006,650.0
21008,nova_jai_0055753,2026-06-05 07:51:00+05:30,2026-06-06 10:25:00+05:30,Jaipur,JAI-03,CLINIC,PHONE,0,nova_jai_0054062,booked,PJAI0027566,False,T002,120.0
21009,nova_jai_0055753,2026-06-05 07:51:00+05:30,2026-06-06 10:25:00+05:30,Jaipur,JAI-03,CLINIC,PHONE,0,nova_jai_0054062,booked,PJAI0027566,False,T015,180.0

##Merged CSV for Legacy and Nova

###Legacy

In [25]:
legacy_path = booking_path / 'legacy'

In [26]:
legacy_df_list = [df_ahmed,df_beng,df_chen,df_hyd,df_jai,df_pun]
df_ahmed.to_csv(legacy_path / "ahmedabad.csv", index=False)
df_beng.to_csv(legacy_path / "bengaluru.csv", index=False)
df_chen.to_csv(legacy_path / "chennai.csv", index=False)
df_hyd.to_csv(legacy_path / "hyderabad.csv", index=False)
df_jai.to_csv(legacy_path / "jaipur.csv", index=False)
df_pun.to_csv(legacy_path / "pune.csv", index=False)
df_legacy_merged = pd.concat(legacy_df_list, ignore_index=True)
df_legacy_merged.to_csv(legacy_path / "merged.csv", index=False)

###Nova

In [27]:
nova_path = booking_path / 'nova'

In [28]:
nova_df_list = [df_chen_nova,df_jai_nova]
df_chen_nova.to_csv(nova_path / "chennai.csv", index=False)
df_jai_nova.to_csv(nova_path / "jaipur.csv", index=False)
df_nova_merged = pd.concat(nova_df_list, ignore_index=True)
df_nova_merged.to_csv(nova_path / "merged.csv", index=False)

In [45]:
df_nova_merged.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,0,NaN,booked,PCHE0044922,False,T007,550.0
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T007,550.0
2,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T011,750.0
3,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,0,NaN,booked,PCHE0047035,False,T004,650.0
4,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,0,NaN,booked,PCHE0051652,False,T004,650.0

In [29]:
df_legacy_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 1252786 entries, 0 to 1252785
Data columns (total 12 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   booking_id    1252786 non-null  str
 1   created_at    1252786 non-null  str
 2   slot_at       1252786 non-null  str
 3   city          1252786 non-null  str
 4   clinic_id     1252786 non-null  str
 5   channel       1252786 non-null  str
 6   source        1252786 non-null  str
 7   patient_id    1252786 non-null  str
 8   patient_name  1252786 non-null  str
 9   test_code     1251496 non-null  str
 10  test_price    1252786 non-null  object
 11  home_fee      1252786 non-null  object
dtypes: object(2), str(10)
memory usage: 114.7+ MB

In [30]:
df_legacy_sample = df_legacy_merged.sample(frac=0.05 , random_state=42)

In [31]:
df_legacy_sample

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
1083233,BK-PUN-202502-006783,06/02/2025 05:37,11/02/2025 09:39,Pune,PUN-02,clinic,phone,PPUN0015549,Renée Pillai,T003,450,0
855191,BK-HYD-202510-050580,10/10/2025 05:52,11/10/2025 13:20,Hyderabad,HYD-01,clinic,phone,PHYD0031866,Manish Menon,PK02,2999,0
676939,BK-CHE-202511-061100,20/11/2025 09:44,25/11/2025 17:33,Chennai,CHE-01,clinic,walkin,PCHE0040727,Renée Nair,T007,550,0
220337,BK-AHM-202605-095233,15/05/2026 04:31,20/05/2026 09:25,Ahmedabad,AHM-02,home,app,PAHM0052986,Ritika Patel,T002,120,150
366974,BK-BLR-202508-057497,23/08/2025 09:10,23/08/2025 09:59,Bangalore,BLR-01,home,phone,PBLR0054642,Pooja Mehta,T010,150,150
...,...,...,...,...,...,...,...,...,...,...,...,...
605335,BK-CHE-202506-029953,23/06/2025 22:38,29/06/2025 07:21,Chennai,CHE-04,home,walkin,PCHE0041377,Rohan Bose,T006,650,150
759754,BK-HYD-202502-009149,26/02/2025 00:50,26/02/2025 07:37,Hyderabad,HYD-01,home,phone,PHYD0014863,Vihaan Joshi,T003,450,150
694836,BK-CHE-202512-068983,10/12/2025 04:25,11/12/2025 07:13,Chennai,CHE-04,clinic,phone,PCHE0049051,Saanvi Khan,PK01,1499,0
889704,BK-HYD-202601-065522,22/01/2026 04:48,26/01/2026 12:56,Hyderabad,HYD-03,clinic,phone,PHYD0007416,Amit Fernandes,T009,800,0
811173,BK-HYD-202506-031428,05/06/2025 10:33,05/06/2025 16:16,Hyderabad,HYD-05,home,phone,PHYD0037212,Ritika Naidu,T003,450,150

In [32]:
df_record_count = df_legacy_sample.groupby(by = ['booking_id','test_code']).agg(record_count = ("booking_id", "count")).reset_index()

In [33]:
df_record_count

                 booking_id  test_code  record_count
0      BK-AHM-202501-000016       T004             1
1      BK-AHM-202501-000056       T008             1
2      BK-AHM-202501-000101       T008             1
3      BK-AHM-202501-000103       T005             1
4      BK-AHM-202501-000108       T004             1
...                     ...        ...           ...
62556  BK-PUN-202606-079946       T016             1
62557  BK-PUN-202606-079962       T010             1
62558  BK-PUN-202606-079964       T001             1
62559  BK-PUN-202606-079976       T005             1
62560            booking_id  test_code             1

[62561 rows x 3 columns]

In [34]:
df_record_count.loc[df_record_count['record_count']>1]

Empty DataFrame
Columns: [booking_id, test_code, record_count]
Index: []

In [35]:
df_legacy_sample.loc[df_legacy_sample['booking_id'] == 'BK-AHM-202502-010486']

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
24036,BK-AHM-202502-010486,20/02/2025 03:21,23/02/2025 08:51,Ahmedabad,AHM-02,clinic,app,PAHM0035250,Nisha Kulkarni,T002,120,0
24037,BK-AHM-202502-010486,20/02/2025 03:21,23/02/2025 08:51,Ahmedabad,AHM-02,clinic,app,PAHM0035250,Nisha Kulkarni,T005,700,0
24035,BK-AHM-202502-010486,20/02/2025 03:21,23/02/2025 08:51,Ahmedabad,AHM-02,clinic,app,PAHM0035250,Nisha Kulkarni,T001,350,0

In [36]:
df_record_count_pop = df_legacy_merged.groupby(by = ['booking_id','test_code']).agg(record_count = ("booking_id", "count")).reset_index()

In [37]:
df_record_count_pop

                   booking_id  test_code  record_count
0        BK-AHM-202501-000001       T004             1
1        BK-AHM-202501-000001       T007             1
2        BK-AHM-202501-000001       T009             1
3        BK-AHM-202501-000002       T004             1
4        BK-AHM-202501-000003       T002             1
...                       ...        ...           ...
1251471  BK-PUN-202606-079978       T009             1
1251472  BK-PUN-202606-079979       T001             1
1251473  BK-PUN-202606-079979       T003             1
1251474  BK-PUN-202606-079979       T008             1
1251475            booking_id  test_code            21

[1251476 rows x 3 columns]

In [38]:
df_record_count_pop.loc[df_record_count_pop['record_count']>1]

         booking_id  test_code  record_count
1251475  booking_id  test_code            21

In [41]:
df_legacy_merged = df_legacy_merged.loc[df_legacy_merged['booking_id'] != 'booking_id']

In [42]:
df_record_count_pop = df_legacy_merged.groupby(by = ['booking_id','test_code']).agg(record_count = ("booking_id", "count")).reset_index()

In [43]:
df_record_count_pop

                   booking_id test_code  record_count
0        BK-AHM-202501-000001      T004             1
1        BK-AHM-202501-000001      T007             1
2        BK-AHM-202501-000001      T009             1
3        BK-AHM-202501-000002      T004             1
4        BK-AHM-202501-000003      T002             1
...                       ...       ...           ...
1251470  BK-PUN-202606-079978      T008             1
1251471  BK-PUN-202606-079978      T009             1
1251472  BK-PUN-202606-079979      T001             1
1251473  BK-PUN-202606-079979      T003             1
1251474  BK-PUN-202606-079979      T008             1

[1251475 rows x 3 columns]

In [44]:
df_record_count_pop.loc[df_record_count_pop['record_count']>1]

Empty DataFrame
Columns: [booking_id, test_code, record_count]
Index: []

In [47]:
df_record_count_nova = df_nova_merged.groupby(by = ['booking_id','test_code']).agg(record_count = ("booking_id", "count")).reset_index()

In [48]:
df_record_count_nova

             booking_id test_code  record_count
0      nova_che_0087556      T007             1
1      nova_che_0087557      T004             1
2      nova_che_0087557      T007             1
3      nova_che_0087557      T011             1
4      nova_che_0087558      T001             1
...                 ...       ...           ...
62413  nova_jai_0055752      T006             1
62414  nova_jai_0055752      T007             1
62415  nova_jai_0055753      T002             1
62416  nova_jai_0055753      T006             1
62417  nova_jai_0055753      T015             1

[62418 rows x 3 columns]

In [49]:
df_record_count_nova.loc[df_record_count_nova['record_count']>1]

Empty DataFrame
Columns: [booking_id, test_code, record_count]
Index: []

In [50]:
df_nova_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 62439 entries, 0 to 62438
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        62439 non-null  str
 1   created_at        62439 non-null  datetime64[us, UTC+05:30]
 2   slot_at           62439 non-null  datetime64[us, UTC+05:30]
 3   city              62439 non-null  str
 4   clinic_id         62439 non-null  str
 5   channel           62439 non-null  str
 6   source            62439 non-null  str
 7   home_fee          62439 non-null  int64
 8   rescheduled_from  3542 non-null   str
 9   status_at_export  62439 non-null  str
 10  patient_id        62439 non-null  str
 11  is_new            62439 non-null  bool
 12  test_code         62418 non-null  str
 13  test_price        62418 non-null  float64
dtypes: bool(1), datetime64[us, UTC+05:30](2), float64(1), int64(1), str(9)
memory usage: 6.3 MB

In [51]:
df_nova_merged['status_at_export'].nunique()

2

In [53]:
df_nova_merged['status_at_export'].unique()

<StringArray>
['booked', 'rescheduled']
Length: 2, dtype: str

In [54]:
df_nova_merged.loc[df_nova_merged['status_at_export'] == 'rescheduled']

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
11,nova_che_0087560,2026-04-07 05:57:00+05:30,2026-04-08 08:46:00+05:30,Chennai,CHE-05,CLINIC,WALKIN,0,NaN,rescheduled,PCHE0037380,False,T007,550.0
25,nova_che_0087566,2026-04-09 01:44:00+05:30,2026-04-12 10:11:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,NaN,rescheduled,PCHE0049932,False,T002,120.0
26,nova_che_0087566,2026-04-09 01:44:00+05:30,2026-04-12 10:11:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,NaN,rescheduled,PCHE0049932,False,T004,650.0
27,nova_che_0087566,2026-04-09 01:44:00+05:30,2026-04-12 10:11:00+05:30,Chennai,CHE-01,CLINIC,PHONE,0,NaN,rescheduled,PCHE0049932,False,T007,550.0
43,nova_che_0087573,2026-04-21 05:43:00+05:30,2026-04-21 07:33:00+05:30,Chennai,CHE-05,HOME,APP,150,NaN,rescheduled,PCHE0041340,False,T007,550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61873,nova_jai_0055523,2026-06-27 01:20:00+05:30,2026-06-29 06:56:00+05:30,Jaipur,JAI-01,CLINIC,APP,0,NaN,rescheduled,PJAI0029322,True,T010,150.0
61964,nova_jai_0055559,2026-06-21 11:05:00+05:30,2026-06-25 11:30:00+05:30,Jaipur,JAI-01,HOME,WALKIN,150,NaN,rescheduled,PJAI0029358,True,T020,450.0
61965,nova_jai_0055559,2026-06-21 11:05:00+05:30,2026-06-25 11:30:00+05:30,Jaipur,JAI-01,HOME,WALKIN,150,NaN,rescheduled,PJAI0029358,True,PK02,2999.0
61974,nova_jai_0055565,2026-06-16 12:44:00+05:30,2026-06-20 19:20:00+05:30,Jaipur,JAI-02,HOME,PHONE,150,NaN,rescheduled,PJAI0029364,True,T002,120.0
61975,nova_jai_0055565,2026-06-16 12:44:00+05:30,2026-06-20 19:20:00+05:30,Jaipur,JAI-02,HOME,PHONE,150,NaN,rescheduled,PJAI0029364,True,T016,160.0

In [55]:
df_nova_merged['rescheduled_from'].unique()

<StringArray>
[               nan, 'nova_che_0090017', 'nova_che_0092841',
 'nova_che_0088334', 'nova_che_0091525', 'nova_che_0093005',
 'nova_che_0090269', 'nova_che_0092354', 'nova_che_0088761',
 'nova_che_0090869',
 ...
 'nova_jai_0054823', 'nova_jai_0054115', 'nova_jai_0053628',
 'nova_jai_0052890', 'nova_jai_0054909', 'nova_jai_0054922',
 'nova_jai_0054877', 'nova_jai_0052936', 'nova_jai_0052790',
 'nova_jai_0054062']
Length: 1501, dtype: str