In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
DATA_DIR = r"/content/drive/MyDrive/Kalpa healthcare"

For Old_Legacy

In [4]:
df_legacy = pd.read_csv(os.path.join(DATA_DIR, "old_legacy.csv"),low_memory=False)
print(df_legacy.head())

             booking_id        created_at           slot_at       city clinic_id channel  source   patient_id patient_name test_code test_price home_fee
0  BK-AHM-202501-000001  08/01/2025 03:16  09/01/2025 08:26  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T009        800        0
1  BK-AHM-202501-000001  08/01/2025 03:16  09/01/2025 08:26  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T004        650        0
2  BK-AHM-202501-000001  08/01/2025 03:16  09/01/2025 08:26  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T007        550        0
3  BK-AHM-202501-000002  03/01/2025 05:18  06/01/2025 13:22  Ahmedabad    AHM-04  clinic     app  PAHM0031384   Nisha Iyer      T004        650        0
4  BK-AHM-202501-000003  27/01/2025 10:46  28/01/2025 13:37  Ahmedabad    AHM-01    home     app  PAHM0027001  Sneha Menon      T003        450      150

In [5]:
#shape of data
df_legacy.shape

(1252786, 12)

In [6]:
#datatype of all columns
df_legacy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252786 entries, 0 to 1252785
Data columns (total 12 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   booking_id    1252786 non-null  object
 1   created_at    1252786 non-null  object
 2   slot_at       1252786 non-null  object
 3   city          1252786 non-null  object
 4   clinic_id     1252786 non-null  object
 5   channel       1252786 non-null  object
 6   source        1252786 non-null  object
 7   patient_id    1252786 non-null  object
 8   patient_name  1252786 non-null  object
 9   test_code     1251496 non-null  object
 10  test_price    1252786 non-null  object
 11  home_fee      1252786 non-null  object
dtypes: object(12)
memory usage: 114.7+ MB

In [7]:
#convert dates
df_legacy['created_at']=pd.to_datetime(df_legacy['created_at'],format='%d/%m/%Y %H:%M',errors='coerce')
df_legacy['slot_at']=pd.to_datetime(df_legacy['slot_at'],format='%d/%m/%Y %H:%M',errors='coerce')

In [8]:
# Convert numeric columns
df_legacy['test_price'] = pd.to_numeric(df_legacy['test_price'], errors='coerce')
df_legacy['home_fee'] = pd.to_numeric(df_legacy['home_fee'], errors='coerce')

In [9]:
# Convert low-cardinality columns
categorical_columns = ['city', 'clinic_id', 'channel', 'source', 'test_code']
df_legacy[categorical_columns] = df_legacy[categorical_columns].astype('category')

In [10]:
# Convert ID columns as strings
df_legacy['booking_id'] = df_legacy['booking_id'].astype('string')
df_legacy['patient_id'] = df_legacy['patient_id'].astype('string')
df_legacy['patient_name'] = df_legacy['patient_name'].astype('string')

In [11]:
df_legacy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252786 entries, 0 to 1252785
Data columns (total 12 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   booking_id    1252786 non-null  string
 1   created_at    1252765 non-null  datetime64[ns]
 2   slot_at       1252765 non-null  datetime64[ns]
 3   city          1252786 non-null  category
 4   clinic_id     1252786 non-null  category
 5   channel       1252786 non-null  category
 6   source        1252786 non-null  category
 7   patient_id    1252786 non-null  string
 8   patient_name  1252786 non-null  string
 9   test_code     1251496 non-null  category
 10  test_price    1252765 non-null  float64
 11  home_fee      1252765 non-null  float64
dtypes: category(5), datetime64[ns](2), float64(2), string(3)
memory usage: 72.9 MB

In [12]:
#missing values
df_legacy.isna().sum()

booking_id         0
created_at        21
slot_at           21
city               0
clinic_id          0
channel            0
source             0
patient_id         0
patient_name       0
test_code       1290
test_price        21
home_fee          21
dtype: int64

In [13]:
#Remove NaN test code
df_legacy = df_legacy.dropna(subset=['test_price'])
df_legacy.isna().sum()

booking_id         0
created_at         0
slot_at            0
city               0
clinic_id          0
channel            0
source             0
patient_id         0
patient_name       0
test_code       1290
test_price         0
home_fee           0
dtype: int64

In [14]:
# Duplicate rows
print("Duplicate rows:", df_legacy.duplicated().sum())

Duplicate rows: 0

In [15]:
#identifying duplicate rows
df_legacy.loc[df_legacy.duplicated()]

Empty DataFrame
Columns: [booking_id, created_at, slot_at, city, clinic_id, channel, source, patient_id, patient_name, test_code, test_price, home_fee]
Index: []

In [16]:
#removing duplicate rows
df_legacy = df_legacy[df_legacy['booking_id']!='booking_id']
print("Duplicate rows:", df_legacy.duplicated().sum())

Duplicate rows: 0

In [17]:
#uniquely indentifying city
df_legacy['city'].unique()

['Ahmedabad', 'Bangalore', 'Bengaluru', 'Chennai', 'Hyderabad', 'Jaipur', 'Pune']
Categories (8, object): ['Ahmedabad', 'Bangalore', 'Bengaluru', 'Chennai', 'Hyderabad', 'Jaipur',
                         'Pune', 'city']

In [18]:
#Standardize city name
df_legacy["city"] = df_legacy["city"].replace("Bangalore", "Bengaluru")

/tmp/ipykernel_4708/1494926984.py:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_legacy["city"] = df_legacy["city"].replace("Bangalore", "Bengaluru")

In [19]:
# Inspect one booking in the legacy system
booking_id = "BK-AHM-202501-000001"
df_legacy.loc[df_legacy["booking_id"] == booking_id]

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,BK-AHM-202501-000001,2025-01-08 03:16:00,2025-01-09 08:26:00,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T009,800.0,0.0
1,BK-AHM-202501-000001,2025-01-08 03:16:00,2025-01-09 08:26:00,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T004,650.0,0.0
2,BK-AHM-202501-000001,2025-01-08 03:16:00,2025-01-09 08:26:00,Ahmedabad,AHM-03,clinic,walkin,PAHM0028525,Saanvi Bose,T007,550.0,0.0

In [20]:
# Count rows and distinct tests per booking
legacy_booking_summary = (df_legacy.groupby("booking_id").agg(row_count=("booking_id", "size"),distinct_tests=("test_code", "nunique")))
legacy_booking_summary.head()

                      row_count  distinct_tests
booking_id
BK-AHM-202501-000001          3               3
BK-AHM-202501-000002          1               1
BK-AHM-202501-000003          4               4
BK-AHM-202501-000004          1               1
BK-AHM-202501-000005          2               2

In [21]:
#repeated test records
summary = df_legacy.groupby("booking_id").agg(row_count=("booking_id", "size"),distinct_tests=("test_code", "nunique"))
len(summary[summary["row_count"] > summary["distinct_tests"]])

1289

In [22]:
#Keep January to June 2025 and 2026
legacy_jan_jun = df_legacy[df_legacy["slot_at"].notna() & (df_legacy["slot_at"].dt.month <= 6) & (df_legacy["slot_at"].dt.year.isin([2025, 2026]))]

In [23]:
#After cleaning
print("Legacy rows after basic cleaning:", len(legacy_jan_jun))
print("Date range:", legacy_jan_jun["slot_at"].min(), "to", legacy_jan_jun["slot_at"].max())
print(legacy_jan_jun["slot_at"].dt.year.value_counts().sort_index())

Legacy rows after basic cleaning: 835514
Date range: 2025-01-01 06:00:00 to 2026-06-30 19:59:00
slot_at
2025    436302
2026    399212
Name: count, dtype: int64

For Nova

In [24]:
df_nova = pd.read_csv(os.path.join(DATA_DIR, "nova.csv"),low_memory=False)
print(df_nova.head())

         booking_id                 created_at                    slot_at     city clinic_id channel  source  home_fee rescheduled_from status_at_export   patient_id  is_new test_code  test_price
0  nova_che_0087556  2026-04-21 01:57:00+05:30  2026-04-25 10:16:00+05:30  Chennai    CHE-01  CLINIC  WALKIN         0              NaN           booked  PCHE0044922   False      T007       550.0
1  nova_che_0087557  2026-03-28 03:02:00+05:30  2026-04-01 09:17:00+05:30  Chennai    CHE-03  CLINIC   PHONE         0              NaN           booked  PCHE0047035   False      T007       550.0
2  nova_che_0087557  2026-03-28 03:02:00+05:30  2026-04-01 09:17:00+05:30  Chennai    CHE-03  CLINIC   PHONE         0              NaN           booked  PCHE0047035   False      T011       750.0
3  nova_che_0087557  2026-03-28 03:02:00+05:30  2026-04-01 09:17:00+05:30  Chennai    CHE-03  CLINIC   PHONE         0              NaN           booked  PCHE0047035   False      T004       650.0
4  nova_che_0087558  2026-04-28 04:46:00+05:30  2026-04-30 08:19:00+05:30  Chennai    CHE-05  CLINIC   PHONE         0              NaN           booked  PCHE0051652   False      T004       650.0

In [25]:
# Check the new system in the same way
df_nova.shape

(62439, 14)

In [26]:
df_nova.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62439 entries, 0 to 62438
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        62439 non-null  object
 1   created_at        62439 non-null  object
 2   slot_at           62439 non-null  object
 3   city              62439 non-null  object
 4   clinic_id         62439 non-null  object
 5   channel           62439 non-null  object
 6   source            62439 non-null  object
 7   home_fee          62439 non-null  int64
 8   rescheduled_from  3542 non-null   object
 9   status_at_export  62439 non-null  object
 10  patient_id        62439 non-null  object
 11  is_new            62439 non-null  bool
 12  test_code         62418 non-null  object
 13  test_price        62418 non-null  float64
dtypes: bool(1), float64(1), int64(1), object(11)
memory usage: 6.3+ MB

In [27]:
#Convert date columns
#df_nova['created_at']

df_nova['created_at'] = pd.to_datetime(df_nova['created_at'].str[:16], format='%Y-%m-%d %H:%M', errors='coerce')
df_nova['slot_at']    = pd.to_datetime(df_nova['slot_at'].str[:16], format='%Y-%m-%d %H:%M', errors='coerce')

# Check: no date should fail to parse
print("created_at not parsed:", df_nova['created_at'].isna().sum())
print("slot_at not parsed:", df_nova['slot_at'].isna().sum())

created_at not parsed: 0
slot_at not parsed: 0

In [28]:
#Convert categorical columns
categorical_columns = ['city','clinic_id','channel','source','status_at_export','test_code']
df_nova[categorical_columns] = df_nova[categorical_columns].astype('category')

In [29]:
#Convert ID columns to string
df_nova['booking_id'] = df_nova['booking_id'].astype('string')
df_nova['patient_id'] = df_nova['patient_id'].astype('string')
df_nova['rescheduled_from'] = df_nova['rescheduled_from'].astype('string')

In [30]:
df_nova.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62439 entries, 0 to 62438
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        62439 non-null  string
 1   created_at        62439 non-null  datetime64[ns]
 2   slot_at           62439 non-null  datetime64[ns]
 3   city              62439 non-null  category
 4   clinic_id         62439 non-null  category
 5   channel           62439 non-null  category
 6   source            62439 non-null  category
 7   home_fee          62439 non-null  int64
 8   rescheduled_from  3542 non-null   string
 9   status_at_export  62439 non-null  category
 10  patient_id        62439 non-null  string
 11  is_new            62439 non-null  bool
 12  test_code         62418 non-null  category
 13  test_price        62418 non-null  float64
dtypes: bool(1), category(6), datetime64[ns](2), float64(1), int64(1), string(3)
memory usage: 3.8 MB

In [31]:
#missing values
df_nova.isna().sum()

booking_id              0
created_at              0
slot_at                 0
city                    0
clinic_id               0
channel                 0
source                  0
home_fee                0
rescheduled_from    58897
status_at_export        0
patient_id              0
is_new                  0
test_code              21
test_price             21
dtype: int64

In [32]:
# Duplicate rows
print("Duplicate rows:", df_nova.duplicated().sum())

Duplicate rows: 0

In [33]:
#uniquely indentifying city
df_nova['city'].unique()

['Chennai', 'Jaipur']
Categories (2, object): ['Chennai', 'Jaipur']

In [34]:
# Inspect one booking in the nova system
booking_id = "nova_che_0087556"
df_nova.loc[df_nova["booking_id"] == booking_id]

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_che_0087556,2026-04-21 01:57:00,2026-04-25 10:16:00,Chennai,CHE-01,CLINIC,WALKIN,0,<NA>,booked,PCHE0044922,False,T007,550.0

In [35]:
# Count rows and distinct tests per booking
nova_booking_summary = (df_nova.groupby("booking_id").agg(row_count=("booking_id", "size"),distinct_tests=("test_code", "nunique")))
nova_booking_summary.head()

                  row_count  distinct_tests
booking_id
nova_che_0087556          1               1
nova_che_0087557          3               3
nova_che_0087558          2               2
nova_che_0087559          5               5
nova_che_0087560          1               1

In [36]:
#repeated test records
summary = df_nova.groupby("booking_id").agg(row_count=("booking_id", "size"),distinct_tests=("test_code", "nunique"))
len(summary[summary["row_count"] > summary["distinct_tests"]])

21

In [37]:
is_rescheduled_original = df_nova["status_at_export"] == "rescheduled"

In [38]:
# Inspect before removing
print("Rows on rescheduled originals:", is_rescheduled_original.sum())                        # expect 3,542
print("Rescheduled original bookings:", df_nova.loc[is_rescheduled_original, "booking_id"].nunique())  # expect 1,500

Rows on rescheduled originals: 3542
Rescheduled original bookings: 1500

In [39]:
df_nova = df_nova.loc[~is_rescheduled_original].copy()
print("Nova rows kept:", len(df_nova))

Nova rows kept: 58897

In [40]:
nova_jan_jun = df_nova[df_nova["slot_at"].notna() & (df_nova["slot_at"].dt.month <= 6) & (df_nova["slot_at"].dt.year.isin([2025, 2026]))]

In [41]:
#After cleaning
print("Nova rows after basic cleaning:", len(nova_jan_jun))
print("Date range:", nova_jan_jun["slot_at"].min(), "to", nova_jan_jun["slot_at"].max())
print(nova_jan_jun["slot_at"].dt.year.value_counts().sort_index())

Nova rows after basic cleaning: 58790
Date range: 2026-04-01 06:01:00 to 2026-06-30 19:54:00
slot_at
2026    58790
Name: count, dtype: int64

# H1 — Is the reported 5% growth real?

Step 1: Combine Legacy and Nova

In [42]:
legacy_jan_jun.head()

             booking_id          created_at             slot_at       city clinic_id channel  source   patient_id patient_name test_code  test_price  home_fee
0  BK-AHM-202501-000001 2025-01-08 03:16:00 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T009       800.0       0.0
1  BK-AHM-202501-000001 2025-01-08 03:16:00 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T004       650.0       0.0
2  BK-AHM-202501-000001 2025-01-08 03:16:00 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525  Saanvi Bose      T007       550.0       0.0
3  BK-AHM-202501-000002 2025-01-03 05:18:00 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384   Nisha Iyer      T004       650.0       0.0
4  BK-AHM-202501-000003 2025-01-27 10:46:00 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001  Sneha Menon      T003       450.0     150.0

In [43]:
nova_jan_jun.head()

         booking_id          created_at             slot_at     city clinic_id channel  source  home_fee rescheduled_from status_at_export   patient_id  is_new test_code  test_price
0  nova_che_0087556 2026-04-21 01:57:00 2026-04-25 10:16:00  Chennai    CHE-01  CLINIC  WALKIN         0             <NA>           booked  PCHE0044922   False      T007       550.0
1  nova_che_0087557 2026-03-28 03:02:00 2026-04-01 09:17:00  Chennai    CHE-03  CLINIC   PHONE         0             <NA>           booked  PCHE0047035   False      T007       550.0
2  nova_che_0087557 2026-03-28 03:02:00 2026-04-01 09:17:00  Chennai    CHE-03  CLINIC   PHONE         0             <NA>           booked  PCHE0047035   False      T011       750.0
3  nova_che_0087557 2026-03-28 03:02:00 2026-04-01 09:17:00  Chennai    CHE-03  CLINIC   PHONE         0             <NA>           booked  PCHE0047035   False      T004       650.0
4  nova_che_0087558 2026-04-28 04:46:00 2026-04-30 08:19:00  Chennai    CHE-05  CLINIC   PHONE         0             <NA>           booked  PCHE0051652   False      T004       650.0

In [44]:
#select the columns needed (clinic_id and source are added for H7 and H9)
legacy_h1 = legacy_jan_jun[["booking_id", "slot_at", "city", "clinic_id", "channel", "source", "patient_id", "test_code", "test_price"]]
nova_h1 = nova_jan_jun[["booking_id", "slot_at", "city", "clinic_id", "channel", "source", "patient_id", "test_code","test_price","rescheduled_from"]]

In [45]:
print(len(legacy_h1))
print(len(nova_h1))

835514
58790

In [46]:
# Legacy: every row is one test line, even if test_code is blank
legacy_h1["is_test"] = True
# Nova: a row is a test only if the booking's test list had a test (empty list -> blank test_code)
nova_h1["is_test"] = nova_h1["test_code"].notna()

/tmp/ipykernel_4708/2228111003.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  legacy_h1["is_test"] = True
/tmp/ipykernel_4708/2228111003.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nova_h1["is_test"] = nova_h1["test_code"].notna()

In [47]:
#add the same rescheduling column to Legacy
legacy_h1["rescheduled_from"] = pd.NA

/tmp/ipykernel_4708/393861247.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  legacy_h1["rescheduled_from"] = pd.NA

In [48]:
#Combine both systems into one dataset
h1_data = pd.concat([legacy_h1, nova_h1],ignore_index=True)
h1_data.head()

             booking_id             slot_at       city clinic_id channel  source   patient_id test_code  test_price  is_test rescheduled_from
0  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T009       800.0     True             <NA>
1  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T004       650.0     True             <NA>
2  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T007       550.0     True             <NA>
3  BK-AHM-202501-000002 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384      T004       650.0     True             <NA>
4  BK-AHM-202501-000003 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001      T003       450.0     True             <NA>

Step 2: Check the combined data

In [49]:
# Check
print("Legacy tests:", legacy_h1["is_test"].sum())                                # expect 835,514
print("Nova tests:", nova_h1["is_test"].sum())                                    # expect 58,770
print("Nova empty bookings (0 tests):", (~nova_h1["is_test"]).sum())              # expect 20

Legacy tests: 835514
Nova tests: 58770
Nova empty bookings (0 tests): 20

In [50]:
#check records by year
print("\nRecords by year:")
print(h1_data["slot_at"].dt.year.value_counts().sort_index())

Records by year:
slot_at
2025    436302
2026    458002
Name: count, dtype: int64

In [51]:
#create year and month columns, and make source / system consistent across both systems
h1_data['year'] = h1_data['slot_at'].dt.strftime('%Y')
h1_data['month'] = h1_data['slot_at'].dt.month
h1_data['source'] = h1_data['source'].astype(str).str.lower()
h1_data['system'] = np.where(h1_data['booking_id'].str.startswith('nova'), 'nova', 'legacy')
h1_data.head()

             booking_id             slot_at       city clinic_id channel  source   patient_id test_code  test_price  is_test rescheduled_from  year  month  system
0  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T009       800.0     True             <NA>  2025      1  legacy
1  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T004       650.0     True             <NA>  2025      1  legacy
2  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T007       550.0     True             <NA>  2025      1  legacy
3  BK-AHM-202501-000002 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384      T004       650.0     True             <NA>  2025      1  legacy
4  BK-AHM-202501-000003 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001      T003       450.0     True             <NA>  2025      1  legacy

Step 3: Removing original bookings of rescheduled

In [52]:
#count rows linked to an original booking
rescheduled_rows = nova_h1[nova_h1["rescheduled_from"].notna()]
print("Rescheduled rows:", len(rescheduled_rows))
rescheduled_rows.head()

Rescheduled rows: 3435
             booking_id             slot_at     city clinic_id channel source   patient_id test_code  test_price  rescheduled_from  is_test
13058  nova_che_0093125 2026-04-20 06:32:00  Chennai    CHE-01  CLINIC  PHONE  PCHE0048651      T010       150.0  nova_che_0090017     True
13059  nova_che_0093126 2026-04-13 06:14:00  Chennai    CHE-03  CLINIC  PHONE  PCHE0053174      T009       800.0  nova_che_0092841     True
13060  nova_che_0093126 2026-04-13 06:14:00  Chennai    CHE-03  CLINIC  PHONE  PCHE0053174      T003       450.0  nova_che_0092841     True
13061  nova_che_0093127 2026-04-09 09:58:00  Chennai    CHE-02    HOME    APP  PCHE0045471      T013       400.0  nova_che_0088334     True
13062  nova_che_0093127 2026-04-09 09:58:00  Chennai    CHE-02    HOME    APP  PCHE0045471      T007       550.0  nova_che_0088334     True

In [53]:
# Find original bookings referenced by Nova replacements
original_ids = rescheduled_rows["rescheduled_from"].unique()
print("Original booking IDs to check:", len(original_ids))

Original booking IDs to check: 1456

In [54]:
#Remove those original bookings from Nova
h1_data = h1_data[~h1_data["booking_id"].isin(original_ids)]
h1_data.head()

             booking_id             slot_at       city clinic_id channel  source   patient_id test_code  test_price  is_test rescheduled_from  year  month  system
0  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T009       800.0     True             <NA>  2025      1  legacy
1  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T004       650.0     True             <NA>  2025      1  legacy
2  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T007       550.0     True             <NA>  2025      1  legacy
3  BK-AHM-202501-000002 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384      T004       650.0     True             <NA>  2025      1  legacy
4  BK-AHM-202501-000003 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001      T003       450.0     True             <NA>  2025      1  legacy

Step 4: Check for H1

In [55]:
#get metric from the data
test_volume=h1_data.groupby('year').agg(total_patients = ('patient_id','nunique'),
                                        total_test = ('is_test','sum'),
                                        total_revenue = ('test_price','sum'),
                                        total_visits = ('booking_id','nunique')).reset_index()
test_volume

   year  total_patients  total_test  total_revenue  total_visits
0  2025           94582      436302    278759748.0        189877
1  2026           98120      457982    315462710.0        195044

In [56]:
# Total tests in each year
old = test_volume.iloc[0]['total_test']
new = test_volume.iloc[1]['total_test']

# Calculate percentage increase
gap = ((new - old) / old) * 100

print('Increase by percent:', round(gap, 2), '%')

Increase by percent: 4.97 %

# H2 - Which branch is short?

In [57]:
test_volume['test_per_visit'] = test_volume['total_test']/test_volume['total_visits']
test_volume['visit_per_patient'] = test_volume['total_visits']/test_volume['total_patients']
test_volume

,year,total_patients,total_test,total_revenue,total_visits,test_per_visit,visit_per_patient
0,2025,94582,436302,278759748.0,189877,2.297814,2.007538
1,2026,98120,457982,315462710.0,195044,2.348096,1.987811

In [58]:
# H1 - Calculate percentage change in metrics

# Get H1 2025 and H1 2026 values
test_per_visit_2025 = test_volume.iloc[0]["test_per_visit"]

test_per_visit_2026 = test_volume.iloc[1]["test_per_visit"]

visit_per_patient_2025 = test_volume.iloc[0]["visit_per_patient"]

visit_per_patient_2026 = test_volume.iloc[1]["visit_per_patient"]

patients_2025 = test_volume.iloc[0]["total_patients"]

patients_2026 = test_volume.iloc[1]["total_patients"]


# Calculate percentage change
test_per_visit_change = ((test_per_visit_2026 - test_per_visit_2025) / test_per_visit_2025) * 100

visit_per_patient_change = ((visit_per_patient_2026 - visit_per_patient_2025)/ visit_per_patient_2025) * 100

patients_change = ((patients_2026 - patients_2025)/patients_2025) * 100

# Display results
print(f"Test per visit change: {test_per_visit_change:.1f}%")
print(f"Visit per patient change: {visit_per_patient_change:.1f}%")
print(f"Patients change: {patients_change:.1f}%")

Test per visit change: 2.2%
Visit per patient change: -1.0%
Patients change: 3.7%

Points of growth from each branch (logs make the three shares add up exactly)

In [59]:
total_ratio = test_volume.loc[1, 'total_test'] / test_volume.loc[0, 'total_test']

tree = pd.DataFrame({'Ratio': {'Patients (P)': patients_2026 / patients_2025,
                               'Visits per patient (V/P)': visit_per_patient_2026 / visit_per_patient_2025,
                               'Tests per visit (T/V)': test_per_visit_2026 / test_per_visit_2025}})
tree['Points of growth'] = np.log(tree['Ratio']) / np.log(total_ratio) * (total_ratio - 1) * 100

# Check: the product of the three ratios must equal the test ratio (1.0497)
print('Product of ratios:', round(tree['Ratio'].prod(), 4), '| Test ratio:', round(total_ratio, 4))
tree.round(4)

Product of ratios: 1.0497 | Test ratio: 1.0497
                           Ratio  Points of growth
Patients (P)              1.0374            3.7629
Visits per patient (V/P)  0.9902           -1.0119
Tests per visit (T/V)     1.0219            2.2180

# H3 - Where is it short?
 Drill down by city and channel

For city

In [60]:
test_volume_city = h1_data.groupby(['year','city']).agg(total_patients = ('patient_id','nunique'),
                                        total_test = ('is_test','sum'),
                                        total_revenue = ('test_price','sum'),
                                        total_visits = ('booking_id','nunique')).reset_index()
test_volume_city

    year       city  total_patients  total_test  total_revenue  total_visits
0   2025  Ahmedabad           16705       76926     49514478.0         33437
1   2025  Bengaluru           21696      100070     64140589.0         43733
2   2025    Chennai           17570       80267     51195944.0         34963
3   2025  Hyderabad           15717       73237     46400272.0         31767
4   2025     Jaipur            9711       45149     28765546.0         19622
5   2025       Pune           13183       60653     38742919.0         26355
6   2026  Ahmedabad           18326       85084     58855170.0         36300
7   2026  Bengaluru           23237      107661     73950220.0         45779
8   2026    Chennai           16689       80758     55640973.0         34245
9   2026  Hyderabad           16990       78674     54165426.0         33496
10  2026     Jaipur            8530       40230     27826848.0         17192
11  2026       Pune           14348       65575     45024073.0         28032

In [61]:
# Calculate visits per patient and tests per visit

test_volume_city["test_per_visit"] = (test_volume_city["total_test"] / test_volume_city["total_visits"])
test_volume_city["visit_per_patient"] = (test_volume_city["total_visits"] / test_volume_city["total_patients"])

# Display the summary
test_volume_city

,year,city,total_patients,total_test,total_revenue,total_visits,test_per_visit,visit_per_patient
0,2025,Ahmedabad,16705,76926,49514478.0,33437,2.300625,2.001616
1,2025,Bengaluru,21696,100070,64140589.0,43733,2.288203,2.015717
2,2025,Chennai,17570,80267,51195944.0,34963,2.295770,1.989926
3,2025,Hyderabad,15717,73237,46400272.0,31767,2.305443,2.021187
4,2025,Jaipur,9711,45149,28765546.0,19622,2.300938,2.020595
5,2025,Pune,13183,60653,38742919.0,26355,2.301385,1.999166
6,2026,Ahmedabad,18326,85084,58855170.0,36300,2.343912,1.980792
7,2026,Bengaluru,23237,107661,73950220.0,45779,2.351755,1.970091
8,2026,Chennai,16689,80758,55640973.0,34245,2.358242,2.051950
9,2026,Hyderabad,16990,78674,54165426.0,33496,2.348758,1.971513
10,2026,Jaipur,8530,40230,27826848.0,17192,2.340042,2.015475
11,2026,Pune,14348,65575,45024073.0,28032,2.339291,1.953722

In [62]:
# H3 - Compare cities between 2025 and 2026

# Make sure year is numeric
test_volume_city["year"] = pd.to_numeric(test_volume_city["year"], errors="coerce")

# Filter each year again
city_2025 = test_volume_city[test_volume_city["year"] == 2025]
city_2026 = test_volume_city[test_volume_city["year"] == 2026]

print(city_2025)
print(city_2026)

   year       city  total_patients  total_test  total_revenue  total_visits  \
0  2025  Ahmedabad           16705       76926     49514478.0         33437
1  2025  Bengaluru           21696      100070     64140589.0         43733
2  2025    Chennai           17570       80267     51195944.0         34963
3  2025  Hyderabad           15717       73237     46400272.0         31767
4  2025     Jaipur            9711       45149     28765546.0         19622
5  2025       Pune           13183       60653     38742919.0         26355

   test_per_visit  visit_per_patient
0        2.300625           2.001616
1        2.288203           2.015717
2        2.295770           1.989926
3        2.305443           2.021187
4        2.300938           2.020595
5        2.301385           1.999166
    year       city  total_patients  total_test  total_revenue  total_visits  \
6   2026  Ahmedabad           18326       85084     58855170.0         36300
7   2026  Bengaluru           23237      107661     73950220.0         45779
8   2026    Chennai           16689       80758     55640973.0         34245
9   2026  Hyderabad           16990       78674     54165426.0         33496
10  2026     Jaipur            8530       40230     27826848.0         17192
11  2026       Pune           14348       65575     45024073.0         28032

    test_per_visit  visit_per_patient
6         2.343912           1.980792
7         2.351755           1.970091
8         2.358242           2.051950
9         2.348758           1.971513
10        2.340042           2.015475
11        2.339291           1.953722

In [63]:
# Use city as the index so matching cities line up
city_2025 = city_2025.set_index("city")
city_2026 = city_2026.set_index("city")

city_comparison = pd.DataFrame({
    "H1 2025 tests": city_2025["total_test"],
    "H1 2026 tests": city_2026["total_test"],
    "H1 2025 patients": city_2025["total_patients"],
    "H1 2026 patients": city_2026["total_patients"],
    "H1 2025 V/P": city_2025["visit_per_patient"],
    "H1 2026 V/P": city_2026["visit_per_patient"],
    "H1 2025 T/V": city_2025["test_per_visit"],
    "H1 2026 T/V": city_2026["test_per_visit"]
})

city_comparison

,H1 2025 tests,H1 2026 tests,H1 2025 patients,H1 2026 patients,H1 2025 V/P,H1 2026 V/P,H1 2025 T/V,H1 2026 T/V
city,,,,,,,,
Ahmedabad,76926,85084,16705,18326,2.001616,1.980792,2.300625,2.343912
Bengaluru,100070,107661,21696,23237,2.015717,1.970091,2.288203,2.351755
Chennai,80267,80758,17570,16689,1.989926,2.051950,2.295770,2.358242
Hyderabad,73237,78674,15717,16990,2.021187,1.971513,2.305443,2.348758
Jaipur,45149,40230,9711,8530,2.020595,2.015475,2.300938,2.340042
Pune,60653,65575,13183,14348,1.999166,1.953722,2.301385,2.339291

In [64]:
result_city = pd.DataFrame()
result_city['H1 2025 tests'] = city_comparison['H1 2025 tests']
result_city['H1 2026 tests'] = city_comparison['H1 2026 tests']

# Calculate percentage growth in tests
result_city["Growth"] = ((city_comparison["H1 2026 tests"] - city_comparison["H1 2025 tests"])/ city_comparison["H1 2025 tests"] * 100).round(1)

# Calculate percentage change in patients
result_city["Patients"] = ((city_comparison["H1 2026 patients"] - city_comparison["H1 2025 patients"])/ city_comparison["H1 2025 patients"] * 100).round(1)

# Calculate percentage change in V/P
result_city["V/P"] = ((city_comparison["H1 2026 V/P"] - city_comparison["H1 2025 V/P"])/ city_comparison["H1 2025 V/P"] * 100).round(1)

# Calculate percentage change in T/V
result_city["T/V"] = ((city_comparison["H1 2026 T/V"] - city_comparison["H1 2025 T/V"]) / city_comparison["H1 2025 T/V"] * 100).round(1)

result_city

           H1 2025 tests  H1 2026 tests  Growth  Patients  V/P  T/V
city
Ahmedabad          76926          85084    10.6       9.7 -1.0  1.9
Bengaluru         100070         107661     7.6       7.1 -2.3  2.8
Chennai            80267          80758     0.6      -5.0  3.1  2.7
Hyderabad          73237          78674     7.4       8.1 -2.5  1.9
Jaipur             45149          40230   -10.9     -12.2 -0.3  1.7
Pune               60653          65575     8.1       8.8 -2.3  1.6

For Channel

In [65]:
h1_data['channel'] = (h1_data['channel'].str.strip().str.lower())

In [66]:
test_volume_channel = h1_data.groupby(['year','channel']).agg(total_patients = ('patient_id','nunique'),
                                        total_test = ('is_test','sum'),
                                        total_revenue = ('test_price','sum'),
                                        total_visits = ('booking_id','nunique')).reset_index()

In [67]:
# Calculate visits per patient and tests per visit

test_volume_channel["test_per_visit"] = (test_volume_channel["total_test"] / test_volume_channel["total_visits"])
test_volume_channel["visit_per_patient"] = (test_volume_channel["total_visits"] / test_volume_channel["total_patients"])

test_volume_channel

,year,channel,total_patients,total_test,total_revenue,total_visits,test_per_visit,visit_per_patient
0,2025,clinic,73399,287186,183174072.0,125170,2.294368,1.705337
1,2025,home,46325,149116,95585676.0,64707,2.304480,1.396805
2,2026,clinic,67304,253110,174621438.0,107790,2.348177,1.601539
3,2026,home,58478,204872,140841272.0,87254,2.347996,1.492082

In [68]:
# Make sure year is numeric
test_volume_channel["year"] = pd.to_numeric(test_volume_channel["year"], errors="coerce")

# Filter each year again
channel_2025 = test_volume_channel[test_volume_channel["year"] == 2025]
channel_2026 = test_volume_channel[test_volume_channel["year"] == 2026]

print(channel_2025)
print(channel_2026)

   year channel  total_patients  total_test  total_revenue  total_visits  \
0  2025  clinic           73399      287186    183174072.0        125170
1  2025    home           46325      149116     95585676.0         64707

   test_per_visit  visit_per_patient
0        2.294368           1.705337
1        2.304480           1.396805
   year channel  total_patients  total_test  total_revenue  total_visits  \
2  2026  clinic           67304      253110    174621438.0        107790
3  2026    home           58478      204872    140841272.0         87254

   test_per_visit  visit_per_patient
2        2.348177           1.601539
3        2.347996           1.492082

In [69]:
# Use channel as the index so matching channel line up
channel_2025 = channel_2025.set_index("channel")
channel_2026 = channel_2026.set_index("channel")

channel_comparison = pd.DataFrame({
    "H1 2025 tests": channel_2025["total_test"],
    "H1 2026 tests": channel_2026["total_test"],
    "H1 2025 patients": channel_2025["total_patients"],
    "H1 2026 patients": channel_2026["total_patients"],
    "H1 2025 V/P": channel_2025["visit_per_patient"],
    "H1 2026 V/P": channel_2026["visit_per_patient"],
    "H1 2025 T/V": channel_2025["test_per_visit"],
    "H1 2026 T/V": channel_2026["test_per_visit"]
})

channel_comparison

,H1 2025 tests,H1 2026 tests,H1 2025 patients,H1 2026 patients,H1 2025 V/P,H1 2026 V/P,H1 2025 T/V,H1 2026 T/V
channel,,,,,,,,
clinic,287186,253110,73399,67304,1.705337,1.601539,2.294368,2.348177
home,149116,204872,46325,58478,1.396805,1.492082,2.304480,2.347996

In [70]:
result_channel = pd.DataFrame()
result_channel['H1 2025 tests'] = channel_comparison['H1 2025 tests']
result_channel['H1 2026 tests'] = channel_comparison['H1 2026 tests']

# Calculate percentage growth in tests
result_channel["Growth"] = ((channel_comparison["H1 2026 tests"] - channel_comparison["H1 2025 tests"])/ channel_comparison["H1 2025 tests"] * 100).round(1)

# Calculate percentage change in patients
result_channel["Patients"] = ((channel_comparison["H1 2026 patients"] - channel_comparison["H1 2025 patients"])/ channel_comparison["H1 2025 patients"] * 100).round(1)

# Calculate percentage change in V/P
result_channel["V/P"] = ((channel_comparison["H1 2026 V/P"] - channel_comparison["H1 2025 V/P"])/ channel_comparison["H1 2025 V/P"] * 100).round(1)

# Calculate percentage change in T/V
result_channel["T/V"] = ((channel_comparison["H1 2026 T/V"] - channel_comparison["H1 2025 T/V"]) / channel_comparison["H1 2025 T/V"] * 100).round(1)

result_channel

         H1 2025 tests  H1 2026 tests  Growth  Patients  V/P  T/V
channel
clinic          287186         253110   -11.9      -8.3 -6.1  2.3
home            149116         204872    37.4      26.2  6.8  1.9

Home share of tests by month

In [71]:
tests_only = h1_data[h1_data['is_test']].copy()
tests_only['is_home'] = tests_only['channel'] == 'home'

home_share = (tests_only.groupby(['month', 'year'])['is_home'].mean() * 100).unstack().round(1)
home_share

year   2025  2026
month
1      34.3  49.4
2      33.9  49.1
3      34.4  48.9
4      34.4  40.1
5      34.0  40.1
6      34.2  40.2

# H4 — Which city is short, and where most

For plan.csv

In [72]:
df_plan = pd.read_csv(os.path.join(DATA_DIR, "plan_2026_H1.csv"),low_memory=False)
df_plan

,city,metric,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06
0,Ahmedabad,test_volume_target_2026,15119,14814,14794,15608,15019,15419
1,Bangalore,test_volume_target_2026,20380,19877,21019,19271,19883,19655
2,Chennai,test_volume_target_2026,15474,15054,16536,15690,15512,15646
3,Hyderabad,test_volume_target_2026,14840,14790,14192,14905,14001,13693
4,Jaipur,test_volume_target_2026,8853,9369,9614,8014,8484,8038
5,Pune,test_volume_target_2026,12336,12389,11727,12128,11779,11818

In [73]:
#shape of data
df_plan.shape

(6, 8)

In [74]:
#datatype of all columns
df_plan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   city     6 non-null      object
 1   metric   6 non-null      object
 2   2026-01  6 non-null      int64
 3   2026-02  6 non-null      int64
 4   2026-03  6 non-null      int64
 5   2026-04  6 non-null      int64
 6   2026-05  6 non-null      int64
 7   2026-06  6 non-null      int64
dtypes: int64(6), object(2)
memory usage: 516.0+ bytes

In [75]:
#standadizing city and metric column
df_plan['city'] = df_plan['city'].str.strip()
df_plan['metric'] = df_plan['metric'].str.strip()

In [76]:
#missing values
df_plan.isna().sum()

city       0
metric     0
2026-01    0
2026-02    0
2026-03    0
2026-04    0
2026-05    0
2026-06    0
dtype: int64

In [77]:
#standardizing city names
df_plan['city']=df_plan['city'].replace('Bangalore','Bengaluru')

In [78]:
df_plan

,city,metric,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06
0,Ahmedabad,test_volume_target_2026,15119,14814,14794,15608,15019,15419
1,Bengaluru,test_volume_target_2026,20380,19877,21019,19271,19883,19655
2,Chennai,test_volume_target_2026,15474,15054,16536,15690,15512,15646
3,Hyderabad,test_volume_target_2026,14840,14790,14192,14905,14001,13693
4,Jaipur,test_volume_target_2026,8853,9369,9614,8014,8484,8038
5,Pune,test_volume_target_2026,12336,12389,11727,12128,11779,11818

For patients.csv

In [79]:
df_patients = pd.read_csv(os.path.join(DATA_DIR, "patients.csv"),low_memory=False)
df_patients.head()

    patient_id     patient_name            phone         dob       city signup_date
0  PAHM0030088  Rahul Fernandes  +91 85778 98441  1988-02-02  Ahmedabad  2023-01-14
1  PAHM0043743   Ananya D'Souza  +91 84824 41827  1992-11-13  Ahmedabad  2025-10-02
2  PAHM0011366      Rohan Mehta  +91 77327 81379  1944-07-05  Ahmedabad  2023-01-18
3  PAHM0009021    Vihaan Pillai  +91 76067 53849  1958-03-06  Ahmedabad  2022-08-06
4  PAHM0052680      Meera Desai  +91 81849 12697  2005-11-01  Ahmedabad  2026-05-19

In [80]:
df_patients.shape

(309217, 6)

In [81]:
df_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309217 entries, 0 to 309216
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   patient_id    309217 non-null  object
 1   patient_name  309217 non-null  object
 2   phone         309217 non-null  object
 3   dob           309217 non-null  object
 4   city          309217 non-null  object
 5   signup_date   309217 non-null  object
dtypes: object(6)
memory usage: 14.2+ MB

In [82]:
# Convert date columns
df_patients['dob'] = pd.to_datetime(df_patients['dob'], errors='coerce')

df_patients['signup_date'] = pd.to_datetime(df_patients['signup_date'], errors='coerce')

In [83]:
#Convert into strings
df_patients['patient_id'] = df_patients['patient_id'].astype('string')
df_patients['patient_name'] = df_patients['patient_name'].astype('string')
df_patients['phone'] = df_patients['phone'].astype('string')
df_patients['city'] = df_patients['city'].astype('string')

In [84]:
df_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309217 entries, 0 to 309216
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   patient_id    309217 non-null  string
 1   patient_name  309217 non-null  string
 2   phone         309217 non-null  string
 3   dob           309217 non-null  datetime64[ns]
 4   city          309217 non-null  string
 5   signup_date   309217 non-null  datetime64[ns]
dtypes: datetime64[ns](2), string(4)
memory usage: 14.2 MB

In [85]:
#missing_values
df_patients.isna().sum()

patient_id      0
patient_name    0
phone           0
dob             0
city            0
signup_date     0
dtype: int64

In [86]:
df_patients['city'].unique()

<StringArray>
['Ahmedabad', 'Bengaluru', 'Chennai', 'Hyderabad', 'Jaipur', 'Pune']
Length: 6, dtype: string

In [87]:
df_patients[['dob', 'signup_date']].head(10)

         dob signup_date
0 1988-02-02  2023-01-14
1 1992-11-13  2025-10-02
2 1944-07-05  2023-01-18
3 1958-03-06  2022-08-06
4 2005-11-01  2026-05-19
5 1993-05-21  2025-06-26
6 1990-06-15  2024-12-09
7 2001-09-06  2023-08-14
8 1996-10-01  2025-12-12
9 1997-10-06  2023-06-19

In [88]:
# 1. Prepare the plan table
plan = df_plan.copy()

# Standardize column names
plan = plan.rename(columns={"City": "city"})

# 2. Check the plan columns
print("Plan columns:", plan.columns.tolist())
display(plan.head())

Plan columns: ['city', 'metric', '2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06']
        city                   metric  2026-01  2026-02  2026-03  2026-04  2026-05  2026-06
0  Ahmedabad  test_volume_target_2026    15119    14814    14794    15608    15019    15419
1  Bengaluru  test_volume_target_2026    20380    19877    21019    19271    19883    19655
2    Chennai  test_volume_target_2026    15474    15054    16536    15690    15512    15646
3  Hyderabad  test_volume_target_2026    14840    14790    14192    14905    14001    13693
4     Jaipur  test_volume_target_2026     8853     9369     9614     8014     8484     8038

In [89]:
# Define the H1 period (January–June 2026)
months = ["2026-01", "2026-02", "2026-03", "2026-04", "2026-05", "2026-06"]

# Calculate the total H1 planned value for each city and metric
plan["plan_h1"] = df_plan[months].sum(axis=1)

# Validate the overall H1 plan by summing all city and metric totals
print("Total H1 plan:", plan["plan_h1"].sum())

# Check which metrics are included in the plan
print("Metrics:", plan["metric"].unique())

Total H1 plan: 515740
Metrics: ['test_volume_target_2026']

In [90]:
# Make city a regular column if it is currently the index
actual = city_comparison.copy().reset_index()

# Standardize the city column
actual = actual.rename(columns={"City": "city"})

# Merge actual data with the plan
h4 = actual.merge(plan[["city", "plan_h1"]],on="city",how="left",validate="one_to_one",indicator=True)

In [91]:
# Validate the join
print("Rows before join:", len(actual))
print("Rows after join:", len(h4))
print("Unmatched cities:")
display(h4.loc[h4["_merge"] != "both", ["city", "_merge"]])

# Remove merge indicator after validation
h4 = h4.drop(columns="_merge")

h4

Rows before join: 6
Rows after join: 6
Unmatched cities:

Empty DataFrame
Columns: [city, _merge]
Index: []

,city,H1 2025 tests,H1 2026 tests,H1 2025 patients,H1 2026 patients,H1 2025 V/P,H1 2026 V/P,H1 2025 T/V,H1 2026 T/V,plan_h1
0,Ahmedabad,76926,85084,16705,18326,2.001616,1.980792,2.300625,2.343912,90773
1,Bengaluru,100070,107661,21696,23237,2.015717,1.970091,2.288203,2.351755,120085
2,Chennai,80267,80758,17570,16689,1.989926,2.051950,2.295770,2.358242,93912
3,Hyderabad,73237,78674,15717,16990,2.021187,1.971513,2.305443,2.348758,86421
4,Jaipur,45149,40230,9711,8530,2.020595,2.015475,2.300938,2.340042,52372
5,Pune,60653,65575,13183,14348,1.999166,1.953722,2.301385,2.339291,72177

In [92]:
# Gap between plan and actual 2026 tests
h4["gap"] = h4["plan_h1"] - h4["H1 2026 tests"]

# Sort cities by gap, largest first
h4 = h4.sort_values("gap", ascending=False)

# Calculate the total row
total_plan = h4["plan_h1"].sum()
total_tests_2025 = h4["H1 2025 tests"].sum()
total_gap = h4["gap"].sum()

total_row = pd.DataFrame([{"city": "Total","plan_uplift": total_plan / total_tests_2025 - 1, "gap": total_gap,"share": 1.0}])

In [93]:
# Calculate plan uplift for each city
h4["plan_uplift"] = (h4["plan_h1"] / h4["H1 2025 tests"] - 1)

# Calculate share of total gap
h4["share"] = h4["gap"] / total_gap

# Select and rename columns
city_result = h4[["city", "plan_uplift", "gap", "share"]].copy()

# Append Total row
city_result = pd.concat([city_result, total_row],ignore_index=True)

In [94]:
# Format percentages and numbers
city_result["Plan uplift"] = city_result["plan_uplift"].map(lambda x: f"{x:+.1%}")
city_result["Gap (tests)"] = city_result["gap"].map(lambda x: f"{x:,.0f}")
city_result["Share of gap"] = city_result["share"].map(lambda x: f"{x:.1%}")

# Final presentation table
city_result = city_result[["city", "Plan uplift", "Gap (tests)", "Share of gap"]].rename(columns={"city": "City"})

city_result

        City Plan uplift Gap (tests) Share of gap
0    Chennai      +17.0%      13,154        22.8%
1  Bengaluru      +20.0%      12,424        21.5%
2     Jaipur      +16.0%      12,142        21.0%
3  Hyderabad      +18.0%       7,747        13.4%
4       Pune      +19.0%       6,602        11.4%
5  Ahmedabad      +18.0%       5,689         9.8%
6      Total      +18.2%      57,758       100.0%

In [95]:
h1_data.head()

             booking_id             slot_at       city clinic_id channel  source   patient_id test_code  test_price  is_test rescheduled_from  year  month  system
0  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T009       800.0     True             <NA>  2025      1  legacy
1  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T004       650.0     True             <NA>  2025      1  legacy
2  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T007       550.0     True             <NA>  2025      1  legacy
3  BK-AHM-202501-000002 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384      T004       650.0     True             <NA>  2025      1  legacy
4  BK-AHM-202501-000003 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001      T003       450.0     True             <NA>  2025      1  legacy

Step 1: Join the h1_data table with patients.csv

In [96]:
tests = h1_data.merge(df_patients[["patient_id", "signup_date"]],on="patient_id",how="left",validate="many_to_one")

In [97]:
# Validate the join
print("Total test records:", len(tests))
print("Missing signup dates:", tests["signup_date"].isna().sum())

Total test records: 894304
Missing signup dates: 0

In [98]:
tests.head()

             booking_id             slot_at       city clinic_id channel  source   patient_id test_code  test_price  is_test rescheduled_from  year  month  system signup_date
0  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T009       800.0     True             <NA>  2025      1  legacy  2024-01-11
1  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T004       650.0     True             <NA>  2025      1  legacy  2024-01-11
2  BK-AHM-202501-000001 2025-01-09 08:26:00  Ahmedabad    AHM-03  clinic  walkin  PAHM0028525      T007       550.0     True             <NA>  2025      1  legacy  2024-01-11
3  BK-AHM-202501-000002 2025-01-06 13:22:00  Ahmedabad    AHM-04  clinic     app  PAHM0031384      T004       650.0     True             <NA>  2025      1  legacy  2024-06-22
4  BK-AHM-202501-000003 2025-01-28 13:37:00  Ahmedabad    AHM-01    home     app  PAHM0027001      T003       450.0     True             <NA>  2025      1  legacy  2023-10-23

Step 2: Keep actual tests and classify patients

In [99]:
tests = tests[tests["is_test"].astype(str).str.strip().str.lower().isin(["true", "1", "yes"])]

In [100]:
# Keep the four growing cities
growing_cities = ["Ahmedabad","Bengaluru","Hyderabad","Pune"]

In [101]:
tests = tests[tests["city"].isin(growing_cities)]

In [102]:
# Convert year to numeric
tests["year"] = pd.to_numeric(tests["year"], errors="coerce")

In [103]:
# Define new vs returning for each half-year
tests["patient_type"] = np.where(tests["signup_date"] >= pd.to_datetime(tests["year"].astype("Int64").astype(str) + "-01-01"),"New","Returning")

In [104]:
tests[["city", "year", "patient_id", "signup_date", "patient_type"]].head()

        city  year   patient_id signup_date patient_type
0  Ahmedabad  2025  PAHM0028525  2024-01-11    Returning
1  Ahmedabad  2025  PAHM0028525  2024-01-11    Returning
2  Ahmedabad  2025  PAHM0028525  2024-01-11    Returning
3  Ahmedabad  2025  PAHM0031384  2024-06-22    Returning
4  Ahmedabad  2025  PAHM0027001  2023-10-23    Returning

Step 3: Calculate test counts by city, year and patient type

In [105]:
# Count actual tests by city, year and patient type
test_counts = (tests.groupby(["city", "year", "patient_type"]).size().unstack(["year", "patient_type"], fill_value=0))

test_counts

year           2025             2026
patient_type    New Returning    New Returning
city
Ahmedabad     29572     47354  36320     48764
Bengaluru     38367     61703  45871     61790
Hyderabad     28379     44858  33282     45392
Pune          23053     37600  27657     37918

Step 4: Calculate new-patient and returning-patient test growth

In [106]:
# Calculate percentage growth from H1 2025 to H1 2026
growth_rows = []

for city in growing_cities:
    row = {"City": city}

    for patient_type in ["New", "Returning"]:
        tests_2025 = len(tests[(tests["city"] == city) & (tests["year"] == 2025) & (tests["patient_type"] == patient_type)])

        tests_2026 = len(tests[(tests["city"] == city) & (tests["year"] == 2026) & (tests["patient_type"] == patient_type)])

        growth = ((tests_2026 / tests_2025 - 1) * 100 if tests_2025 > 0 else np.nan)

        row[f"{patient_type}-patient tests"] = growth

    growth_rows.append(row)

growth_table = pd.DataFrame(growth_rows)

growth_table

        City  New-patient tests  Returning-patient tests
0  Ahmedabad          22.818883                 2.977573
1  Bengaluru          19.558475                 0.140998
2  Hyderabad          17.276860                 1.190423
3       Pune          19.971370                 0.845745

Step 5: Add the plan uplift and format the final table

In [107]:
# Get plan uplift for the four growing cities
plan_table = h4[["city","plan_h1","H1 2025 tests"]]

plan_table["Plan"] = (plan_table["plan_h1"] / plan_table["H1 2025 tests"] - 1) * 100

/tmp/ipykernel_4708/514336739.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  plan_table["Plan"] = (plan_table["plan_h1"] / plan_table["H1 2025 tests"] - 1) * 100

In [108]:
print("Plan table:", plan_table.columns.tolist())
print("Growth table:", growth_table.columns.tolist())

Plan table: ['city', 'plan_h1', 'H1 2025 tests', 'Plan']
Growth table: ['City', 'New-patient tests', 'Returning-patient tests']

In [109]:
growth_table = growth_table.rename(columns={"City": "city"})

In [110]:
plan_table = plan_table.rename(columns={"City": "city"})

In [111]:
# Merge with new vs returning patient growth
final_h4 = growth_table.merge(plan_table[["city", "Plan"]],on="city",how="left",validate="one_to_one")

In [112]:
# Format percentages
for col in ["New-patient tests","Returning-patient tests","Plan"]:
    final_h4[col] = final_h4[col].map(lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A")

final_h4

        city New-patient tests Returning-patient tests    Plan
0  Ahmedabad            +22.8%                   +3.0%  +18.0%
1  Bengaluru            +19.6%                   +0.1%  +20.0%
2  Hyderabad            +17.3%                   +1.2%  +18.0%
3       Pune            +20.0%                   +0.8%  +19.0%

Split the gap: Chennai + Jaipur vs the other four cities

In [113]:
h4['group'] = np.where(h4['city'].isin(['Chennai', 'Jaipur']), 'Chennai + Jaipur', 'Other four')

group_gap = h4.groupby('group')[['gap']].sum()
group_gap['share'] = (group_gap['gap'] / group_gap['gap'].sum() * 100).round(1)
group_gap

                    gap  share
group
Chennai + Jaipur  25296   43.8
Other four        32462   56.2

#H5 — Bookings per patient across months

In [114]:
# Visits per patient (V/P) by city, month and year
vp = h1_data.groupby(['city', 'month', 'year']).agg(visits=('booking_id', 'nunique'),
                                                    patients=('patient_id', 'nunique'))
vp['V/P'] = vp['visits'] / vp['patients']
vp = vp['V/P'].unstack()
vp.head()

year                 2025      2026
city      month
Ahmedabad 1      1.209302  1.193445
          2      1.195858  1.200848
          3      1.183001  1.202119
          4      1.196343  1.200727
          5      1.191869  1.188825

Step 1: half-year V/P (check against H2: 2.0075 and 1.9878)

In [115]:
vp_2025 = test_volume.loc[0, 'visit_per_patient']
vp_2026 = test_volume.loc[1, 'visit_per_patient']
vp_change = (vp_2026 / vp_2025 - 1) * 100
print(f'{vp_2025:.4f} -> {vp_2026:.4f} ({vp_change:+.1f}%)')

2.0075 -> 1.9878 (-1.0%)

Step 2 and 3: V/P change by city, and month by month (January with January, not January with June)

In [116]:
print('By city (from H3):'); print(result_city['V/P'])

monthly_change = (vp['2026'] / vp['2025'] - 1) * 100
print(f'Monthly year-on-year moves by city: {monthly_change.min():+.1f}% to {monthly_change.max():+.1f}%')

By city (from H3):
city
Ahmedabad   -1.0
Bengaluru   -2.3
Chennai      3.1
Hyderabad   -2.5
Jaipur      -0.3
Pune        -2.3
Name: V/P, dtype: float64
Monthly year-on-year moves by city: -2.8% to +4.4%

Step 4: cohort - what share of H1 2025 patients also visited in H1 2026, per city

In [117]:
patients_2025 = h1_data[h1_data['year'] == '2025'].groupby('city')['patient_id'].unique()
patients_2026 = h1_data[h1_data['year'] == '2026'].groupby('city')['patient_id'].unique()

return_rate = pd.Series({c: np.isin(patients_2025[c], patients_2026[c]).mean() * 100 for c in patients_2025.index})
return_rate.round(1)

Ahmedabad    32.7
Bengaluru    32.5
Chennai      34.0
Hyderabad    32.3
Jaipur       32.8
Pune         32.8
dtype: float64

In [118]:
results = pd.DataFrame({'Check': ['Half-year V/P', 'Monthly year-on-year moves', 'Chennai', 'Jaipur', 'H1 2025 patients returning in H1 2026'],
                        'Finding': [f'{vp_2025:.4f} -> {vp_2026:.4f} ({vp_change:+.1f}%)',
                                    f'Between {monthly_change.min():+.1f}% and {monthly_change.max():+.1f}%, no city or month pattern',
                                    f"{result_city.loc['Chennai', 'V/P']:+.1f}%",
                                    f"{result_city.loc['Jaipur', 'V/P']:+.1f}%",
                                    f'{return_rate.min():.1f}-{return_rate.max():.1f}% in every city']})
results

                                   Check                                            Finding
0                          Half-year V/P                           2.0075 -> 1.9878 (-1.0%)
1             Monthly year-on-year moves  Between -2.8% and +4.4%, no city or month pattern
2                                Chennai                                              +3.1%
3                                 Jaipur                                              -0.3%
4  H1 2025 patients returning in H1 2026                           32.3-34.0% in every city

**Verdict H5: rejected as a main cause.** V/P fell 1.0% (about 1 point of growth, not the 13-point gap), the change has no pattern, Chennai went up, and the return rate is 32-34% in every city. The return rate is kept as evidence for H4.

# H6 — No-shows

For collections .csv

In [119]:
df_collections = pd.read_csv(os.path.join(DATA_DIR, "collections.csv"),low_memory=False)
print(df_collections.head())

             booking_id clinic_id channel     status         collected_at  \
0  BK-AHM-202501-000001    AHM-03  clinic  collected  2025-01-09 09:09:00
1  BK-AHM-202501-000002    AHM-04  clinic  collected  2025-01-06 13:44:00
2  BK-AHM-202501-000003    AHM-01    home  collected  2025-01-28 13:37:00
3  BK-AHM-202501-000005    AHM-03  clinic  collected  2025-01-11 09:59:00
4  BK-AHM-202501-000006    AHM-04    home  collected  2025-01-11 12:39:00

  phlebotomist_id
0             NaN
1             NaN
2        PHAHM047
3             NaN
4        PHAHM011

In [120]:
df_collections.shape

(552492, 6)

In [121]:
df_collections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552492 entries, 0 to 552491
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   booking_id       552492 non-null  object
 1   clinic_id        552492 non-null  object
 2   channel          552492 non-null  object
 3   status           552492 non-null  object
 4   collected_at     473320 non-null  object
 5   phlebotomist_id  208554 non-null  object
dtypes: object(6)
memory usage: 25.3+ MB

In [122]:
#convert to string:
df_collections['booking_id'] = df_collections['booking_id'].astype('string')
df_collections['clinic_id'] = df_collections['clinic_id'].astype('string')
df_collections['channel'] = df_collections['channel'].astype('string')
df_collections['status'] = df_collections['status'].astype('string')
df_collections['phlebotomist_id'] = df_collections['phlebotomist_id'].astype('string')

In [123]:
#convert to datetime:
df_collections['collected_at'] = pd.to_datetime(df_collections['collected_at'],errors='coerce')

In [124]:
df_collections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552492 entries, 0 to 552491
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   booking_id       552492 non-null  string
 1   clinic_id        552492 non-null  string
 2   channel          552492 non-null  string
 3   status           552492 non-null  string
 4   collected_at     473320 non-null  datetime64[ns]
 5   phlebotomist_id  208554 non-null  string
dtypes: datetime64[ns](1), string(5)
memory usage: 25.3 MB

In [125]:
#missing values
df_collections.isna().sum()

booking_id              0
clinic_id               0
channel                 0
status                  0
collected_at        79172
phlebotomist_id    343938
dtype: int64

In [126]:
df_collections[(df_collections['collected_at'].isna()) & (df_collections['status']!='no_show')]

Empty DataFrame
Columns: [booking_id, clinic_id, channel, status, collected_at, phlebotomist_id]
Index: []

In [127]:
df_collections[df_collections['status']=='no_show']

,booking_id,clinic_id,channel,status,collected_at,phlebotomist_id
13,BK-AHM-202501-000015,AHM-01,clinic,no_show,NaT,<NA>
14,BK-AHM-202501-000016,AHM-03,clinic,no_show,NaT,<NA>
20,BK-AHM-202501-000022,AHM-02,clinic,no_show,NaT,<NA>
21,BK-AHM-202501-000023,AHM-03,clinic,no_show,NaT,<NA>
31,BK-AHM-202501-000033,AHM-04,home,no_show,NaT,PHAHM030
...,...,...,...,...,...,...
552452,BK-PUN-202606-079963,PUN-01,clinic,no_show,NaT,<NA>
552453,BK-PUN-202606-079964,PUN-01,clinic,no_show,NaT,<NA>
552454,BK-PUN-202606-079965,PUN-03,clinic,no_show,NaT,<NA>
552462,BK-PUN-202606-079973,PUN-01,clinic,no_show,NaT,<NA>
552465,BK-PUN-202606-079976,PUN-03,clinic,no_show,NaT,<NA>

In [128]:
# Duplicate rows
print("Duplicate rows:", df_collections.duplicated().sum())

Duplicate rows: 2894

In [129]:
booking_id = df_collections[df_collections.duplicated()]['booking_id']

In [130]:
df_collections[df_collections['booking_id'].isin(booking_id)].sort_values(by = 'booking_id')

,booking_id,clinic_id,channel,status,collected_at,phlebotomist_id
30,BK-AHM-202501-000032,AHM-04,clinic,collected,2025-01-02 12:22:00,<NA>
5446,BK-AHM-202501-000032,AHM-04,clinic,collected,2025-01-02 12:22:00,<NA>
97,BK-AHM-202501-000102,AHM-01,clinic,collected,2025-01-30 13:51:00,<NA>
5447,BK-AHM-202501-000102,AHM-01,clinic,collected,2025-01-30 13:51:00,<NA>
1005,BK-AHM-202501-001036,AHM-01,clinic,collected,2025-01-11 13:47:00,<NA>
...,...,...,...,...,...,...
474457,nova_jai_0053904,JAI-01,clinic,collected,2026-06-06 09:06:00,<NA>
472923,nova_jai_0054008,JAI-02,clinic,collected,2026-06-24 14:31:00,<NA>
474458,nova_jai_0054008,JAI-02,clinic,collected,2026-06-24 14:31:00,<NA>
473371,nova_jai_0054471,JAI-02,clinic,collected,2026-06-29 10:37:00,<NA>
474459,nova_jai_0054471,JAI-02,clinic,collected,2026-06-29 10:37:00,<NA>

In [131]:
df_collections = df_collections.drop_duplicates()

In [132]:
# Duplicate rows
print("Duplicate rows:", df_collections.duplicated().sum())

Duplicate rows: 0

Step 1: one row per visit. `ops_id` is the ID that collections use (the original ID for a rescheduled Nova visit).

In [133]:
visits = h1_data.drop_duplicates('booking_id')[['booking_id', 'rescheduled_from', 'slot_at', 'city', 'year', 'system', 'patient_id', 'channel']].copy()
visits['ops_id'] = visits['rescheduled_from'].fillna(visits['booking_id'])
print('Visits:', len(visits), '| rescheduled replacements:', visits['rescheduled_from'].notna().sum())

Visits: 384921 | rescheduled replacements: 1456

Step 2 to 4: join collections on `ops_id`. The row count must not change.

In [134]:
df_collections['status'] = df_collections['status'].str.strip().str.lower()
print('One row per booking_id:', df_collections['booking_id'].is_unique)

no_show_data = visits.merge(df_collections[['booking_id', 'status']].rename(columns={'booking_id': 'ops_id'}), on='ops_id', how='left')
print('Visits in:', len(visits), '| out:', len(no_show_data))

One row per booking_id: True
Visits in: 384921 | out: 384921

Step 5: share of visits with no collection record (Chennai and Jaipur should be about 3.4-3.5% in 2026, close to the others)

In [135]:
no_record = no_show_data.assign(no_record=no_show_data['status'].isna())
(no_record.groupby(['city', 'year'])['no_record'].mean() * 100).unstack().round(2)

year       2025  2026
city
Ahmedabad  3.89  3.94
Bengaluru  3.96  3.91
Chennai    3.86  3.44
Hyderabad  3.96  4.03
Jaipur     4.18  3.48
Pune       3.71  3.90

Step 6: no-show rate = no-shows / visits that have a collection record

In [136]:
has_record = no_show_data[no_show_data['status'].notna()].copy()
has_record['no_show'] = (has_record['status'] == 'no_show').astype(float)

rate = (has_record.groupby(['city', 'year'])['no_show'].mean() * 100).unstack()
rate.loc['All'] = has_record.groupby('year')['no_show'].mean() * 100
rate['Change (pts)'] = rate['2026'] - rate['2025']
rate.round(2)

year        2025   2026  Change (pts)
city
Ahmedabad  14.45  14.21         -0.24
Bengaluru  14.67  13.84         -0.84
Chennai    14.93  14.33         -0.59
Hyderabad  14.39  13.86         -0.53
Jaipur     14.37  13.72         -0.65
Pune       14.47  13.98         -0.49
All        14.57  14.01         -0.57

Nova cities, April to June 2026, by system

In [137]:
nova_q2 = has_record[(has_record['year'] == '2026') & (has_record['slot_at'].dt.month >= 4) & has_record['city'].isin(['Chennai', 'Jaipur'])]
(nova_q2.groupby(['city', 'system'])['no_show'].mean() * 100).round(1)

city     system
Chennai  nova      14.7
Jaipur   nova      14.3
Name: no_show, dtype: float64

**Verdict H6: rejected.** The no-show rate fell from 14.57% to 14.01%, and fell in every city (by 0.24 to 0.84 points). Nova's rate in Chennai and Jaipur is in line with the legacy cities.

# H7 - Patient decline: when, which channel, and is itthe migration?

Step 1: join `signup_date` and label each row new or returning (new = signed up on or after 1 January of that year)

In [138]:
h7 = h1_data.merge(df_patients[['patient_id', 'signup_date']], on='patient_id', how='left', validate='many_to_one')
print('Rows:', len(h1_data), '->', len(h7), '| patient_ids without a signup date:', h7['signup_date'].isna().sum())

h7['ptype'] = np.where(h7['signup_date'].dt.year >= h7['year'].astype(int), 'new', 'returning')
h7['quarter'] = h7['slot_at'].dt.quarter

Rows: 894304 -> 894304 | patient_ids without a signup date: 0

## 7a: Who was lost? Tests and patients by city and patient type

In [139]:
a = h7.groupby(['city', 'ptype', 'year']).agg(tests=('is_test', 'sum'), patients=('patient_id', 'nunique')).unstack()

h7a = pd.DataFrame({'Test growth %': (a['tests']['2026'] / a['tests']['2025'] - 1) * 100,
                    'Patient growth %': (a['patients']['2026'] / a['patients']['2025'] - 1) * 100}).round(1)
h7a.loc[['Chennai', 'Jaipur']]

                   Test growth %  Patient growth %
city    ptype
Chennai new                -18.3             -26.6
        returning           12.2               9.2
Jaipur  new                -31.6             -34.3
        returning            2.5               2.9

In [140]:
# New patients in the other four cities
h7a.drop(['Chennai', 'Jaipur'], level='city').xs('new', level='ptype')

           Test growth %  Patient growth %
city
Ahmedabad           22.8              19.4
Bengaluru           19.6              15.1
Hyderabad           17.3              16.0
Pune                20.0              17.0

## 7b: When, and is it the migration?  New patients by month, year on year

In [141]:
new_pat = h7[h7['ptype'] == 'new'].groupby(['city', 'month', 'year'])['patient_id'].nunique().unstack()
new_by_month = ((new_pat['2026'] / new_pat['2025'] - 1) * 100).unstack().round(1)
new_by_month.columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
new_by_month.loc[['Chennai', 'Jaipur']]

          Jan   Feb   Mar   Apr   May   Jun
city
Chennai -24.4 -15.9 -26.6 -24.4 -25.7 -21.8
Jaipur  -34.5 -37.7 -38.5 -28.9 -33.3 -29.5

Tests by quarter, year on year. Q1 2026 is entirely legacy, Q2 is Nova.

In [142]:
tq = h7.groupby(['city', 'quarter', 'year'])['is_test'].sum().unstack()
((tq['2026'] / tq['2025'] - 1) * 100).unstack().round(1).loc[['Chennai', 'Jaipur']]

quarter     1    2
city
Chennai   3.7 -2.5
Jaipur  -14.6 -6.7

Independent check: signups per quarter in `patients.csv` (does not use the booking files)

In [143]:
df_patients['signup_quarter'] = df_patients['signup_date'].dt.to_period('Q')
df_patients['group'] = np.where(df_patients['city'].isin(['Chennai', 'Jaipur']), df_patients['city'], 'Other four')

signups = df_patients.groupby(['signup_quarter', 'group']).size().unstack()
signups.loc['2025Q1':'2026Q2']

group           Chennai  Jaipur  Other four
signup_quarter
2025Q1             3553    2123       13901
2025Q2             3571    1863       13678
2025Q3             3580    1861       13296
2025Q4             3553    1887       12880
2026Q1             2696    1350       16409
2026Q2             2550    1292       15795

## 7c: Where inside Chennai and Jaipur?  New-patient growth by clinic, source and channel

In [144]:
new_weak = h7[(h7['ptype'] == 'new') & h7['city'].isin(['Chennai', 'Jaipur'])]

def new_growth(col):
    g = new_weak.groupby(['city', col, 'year'])['patient_id'].nunique().unstack()
    g['Growth %'] = ((g['2026'] / g['2025'] - 1) * 100).round(1)
    return g

new_growth('clinic_id')     # JAI-05 opened in 2026, so it has no 2025 base

year                 2025    2026  Growth %
city    clinic_id
Chennai CHE-01     3335.0  2500.0     -25.0
        CHE-02     2424.0  1852.0     -23.6
        CHE-03     1972.0  1523.0     -22.8
        CHE-04     1597.0  1249.0     -21.8
        CHE-05     1340.0  1044.0     -22.1
Jaipur  JAI-01     2130.0  1382.0     -35.1
        JAI-02     1499.0   982.0     -34.5
        JAI-03     1257.0   820.0     -34.8
        JAI-04      979.0   674.0     -31.2
        JAI-05        NaN    58.0       NaN

In [145]:
new_growth('source')

year            2025  2026  Growth %
city    source
Chennai app     4571  3377     -26.1
        phone   3195  2408     -24.6
        walkin  1740  1373     -21.1
Jaipur  app     2741  1766     -35.6
        phone   1685  1139     -32.4
        walkin   990   638     -35.6

In [146]:
new_growth('channel')

year             2025  2026  Growth %
city    channel
Chennai clinic   5441  3570     -34.4
        home     3219  3013      -6.4
Jaipur  clinic   3041  1796     -40.9
        home     1889  1514     -19.9

**Verdict H7a: supported.** Chennai and Jaipur lost new patients (-26.6% and -34.3%); returning patients grew. In the other four cities new patients grew 15-19%.

**H7b: the migration is rejected.** New patients were already down in January, before Nova went live in April. The drop is the same size before and after April, it shows on legacy in Q1, and the patient master shows the same fall in signups. A recording problem would start in April and show only in Nova data.

**H7c:** the loss is in every clinic, source and month, with clinic patients hit hardest and home patients cushioned by the free-collection offer. The cause is unresolved: there is no competitor, pricing or referral data in the pack.

# H8 — Payment delays

For invoices .csv

In [147]:
df_invoices = pd.read_csv(os.path.join(DATA_DIR, "invoices.csv"),low_memory=False)
print(df_invoices.head())

        invoice_id invoice_date            booking_id   patient_id       city  \
0  INV-2024-000001   2024-12-30  BK-BLR-202501-006763  PBLR0044005  Bengaluru
1  INV-2024-000002   2024-12-30  BK-BLR-202501-007103  PBLR0044345  Bengaluru
2  INV-2024-000003   2024-12-31  BK-PUN-202501-001985  PPUN0008860       Pune
3  INV-2024-000004   2024-12-31  BK-CHE-202501-001176  PCHE0012203    Chennai
4  INV-2025-000001   2025-01-01  BK-AHM-202501-005119  PAHM0034226  Ahmedabad

  channel    amount
0  clinic    280.00
1  clinic  1,070.00
2  clinic    350.00
3    home  3,299.00
4  clinic  2,649.00

In [148]:
df_invoices.shape

(470776, 7)

In [149]:
df_invoices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470776 entries, 0 to 470775
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_id    470776 non-null  object
 1   invoice_date  470776 non-null  object
 2   booking_id    470776 non-null  object
 3   patient_id    470776 non-null  object
 4   city          470776 non-null  object
 5   channel       470776 non-null  object
 6   amount        470776 non-null  object
dtypes: object(7)
memory usage: 25.1+ MB

In [150]:
# convert to datetime
df_invoices['invoice_date'] = pd.to_datetime(df_invoices['invoice_date'],errors='coerce')

In [151]:
#convert to string
df_invoices['invoice_id'] = df_invoices['invoice_id'].astype('string')
df_invoices['booking_id'] = df_invoices['booking_id'].astype('string')
df_invoices['patient_id'] = df_invoices['patient_id'].astype('string')
df_invoices['city'] = df_invoices['city'].astype('string')
df_invoices['channel'] = df_invoices['channel'].astype('string')

In [152]:
#convert to float
df_invoices['amount'] = df_invoices['amount'].str.replace(',','')
df_invoices['amount'] = pd.to_numeric(df_invoices['amount'], errors='coerce').astype(float)

In [153]:
df_invoices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470776 entries, 0 to 470775
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_id    470776 non-null  string
 1   invoice_date  470776 non-null  datetime64[ns]
 2   booking_id    470776 non-null  string
 3   patient_id    470776 non-null  string
 4   city          470776 non-null  string
 5   channel       470776 non-null  string
 6   amount        470776 non-null  float64
dtypes: datetime64[ns](1), float64(1), string(5)
memory usage: 25.1 MB

In [154]:
df_invoices.head()

,invoice_id,invoice_date,booking_id,patient_id,city,channel,amount
0,INV-2024-000001,2024-12-30,BK-BLR-202501-006763,PBLR0044005,Bengaluru,clinic,280.0
1,INV-2024-000002,2024-12-30,BK-BLR-202501-007103,PBLR0044345,Bengaluru,clinic,1070.0
2,INV-2024-000003,2024-12-31,BK-PUN-202501-001985,PPUN0008860,Pune,clinic,350.0
3,INV-2024-000004,2024-12-31,BK-CHE-202501-001176,PCHE0012203,Chennai,home,3299.0
4,INV-2025-000001,2025-01-01,BK-AHM-202501-005119,PAHM0034226,Ahmedabad,clinic,2649.0

In [155]:
df_invoices.isna().sum()

invoice_id      0
invoice_date    0
booking_id      0
patient_id      0
city            0
channel         0
amount          0
dtype: int64

In [156]:
df_invoices['city'].unique()

<StringArray>
['Bengaluru', 'Pune', 'Chennai', 'Ahmedabad', 'Jaipur', 'Hyderabad']
Length: 6, dtype: string

In [157]:
df_invoices['channel'].unique()

<StringArray>
['clinic', 'home']
Length: 2, dtype: string

For payments_gateway_export .csv

In [158]:
df_payments_gateway = pd.read_csv(os.path.join(DATA_DIR, "payments_gateway_export.csv"),low_memory=False)
print(df_payments_gateway.head())

       payment_id notes_invoice_ref  amount_paise    status  created_at_epoch  \
0  pay_0000000002   INV-2024-000002        107000  captured        1735577378
1  pay_0000000003   INV-2024-000003         35000  captured        1735653947
2  pay_0000000001   INV-2024-000001         28000  captured        1735996468
3  pay_0000000004   INV-2024-000004        329900  captured        1736099388
4  pay_0000000005  inv-2025-000001         264900  captured        1736952805

  method  settlement_id
0    upi  setl_67733400
1    upi  setl_67748580
2    upi  setl_6779cb80
3   card  setl_677b1d00
4    upi  setl_67884c00

In [159]:
df_payments_gateway.shape

(473507, 7)

In [160]:
df_payments_gateway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473507 entries, 0 to 473506
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   payment_id         473507 non-null  object
 1   notes_invoice_ref  473507 non-null  object
 2   amount_paise       473507 non-null  int64
 3   status             473507 non-null  object
 4   created_at_epoch   473507 non-null  int64
 5   method             473507 non-null  object
 6   settlement_id      455469 non-null  object
dtypes: int64(2), object(5)
memory usage: 25.3+ MB

In [161]:
#convert to string
df_payments_gateway['payment_id'] = df_payments_gateway['payment_id'].astype('string')
df_payments_gateway['notes_invoice_ref'] = df_payments_gateway['notes_invoice_ref'].astype('string')
df_payments_gateway['status'] = df_payments_gateway['status'].astype('string')
df_payments_gateway['method'] = df_payments_gateway['method'].astype('string')
df_payments_gateway['settlement_id'] = df_payments_gateway['settlement_id'].astype('string')

In [162]:
df_payments_gateway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473507 entries, 0 to 473506
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   payment_id         473507 non-null  string
 1   notes_invoice_ref  473507 non-null  string
 2   amount_paise       473507 non-null  int64
 3   status             473507 non-null  string
 4   created_at_epoch   473507 non-null  int64
 5   method             473507 non-null  string
 6   settlement_id      455469 non-null  string
dtypes: int64(2), string(5)
memory usage: 25.3 MB

In [163]:
df_payments_gateway.isna().sum()

payment_id               0
notes_invoice_ref        0
amount_paise             0
status                   0
created_at_epoch         0
method                   0
settlement_id        18038
dtype: int64

In [164]:
df_payments_gateway[(df_payments_gateway['settlement_id'].isna())]

,payment_id,notes_invoice_ref,amount_paise,status,created_at_epoch,method,settlement_id
14,pay_000000000f,INV2025000011,95000,failed,1735732240,upi,<NA>
89,pay_000000005a,INV-2025-000089,349800,failed,1736509114,card,<NA>
128,pay_0000000081,INV-2025-000129,135000,failed,1735757203,upi,<NA>
148,pay_0000000095,INV-2025-000148,299900,failed,1735845289,upi,<NA>
207,pay_00000000d0,INV2025000209,65000,failed,1736502322,card,<NA>
...,...,...,...,...,...,...,...
473429,pay_0000073936,INV2026162624,80000,failed,1783605353,upi,<NA>
473438,pay_000007393f,INV-2026-162634,299900,failed,1784061609,upi,<NA>
473446,pay_000007394b,INV-2026-162680,564800,failed,1783251542,card,<NA>
473472,pay_0000073971,INV-2026-162764,149900,failed,1783284034,cash,<NA>
473499,pay_000007399b,inv-2026-162858,304900,failed,1783024965,upi,<NA>

In [165]:
df_payments_gateway[(df_payments_gateway['settlement_id'].isna())&(df_payments_gateway['status']!='failed')]

Empty DataFrame
Columns: [payment_id, notes_invoice_ref, amount_paise, status, created_at_epoch, method, settlement_id]
Index: []

In [166]:
df_payments_gateway.duplicated().sum()

np.int64(0)

In [167]:
df_payments_gateway['status'].unique()

<StringArray>
['captured', 'failed']
Length: 2, dtype: string

In [168]:
df_payments_gateway['method'].unique()

<StringArray>
['upi', 'card', 'cash', 'netbanking']
Length: 4, dtype: string

In [169]:
df_payments_gateway['notes_invoice_ref'] = (df_payments_gateway['notes_invoice_ref'].astype('string').str.strip().str.upper()
    .str.replace(r'^INV-?', 'INV-', regex=True)
    .str.replace(r'^(INV-\d{4})(?!-)', r'\1-', regex=True)
)

In [170]:
df_payments_gateway.head()

,payment_id,notes_invoice_ref,amount_paise,status,created_at_epoch,method,settlement_id
0,pay_0000000002,INV-2024-000002,107000,captured,1735577378,upi,setl_67733400
1,pay_0000000003,INV-2024-000003,35000,captured,1735653947,upi,setl_67748580
2,pay_0000000001,INV-2024-000001,28000,captured,1735996468,upi,setl_6779cb80
3,pay_0000000004,INV-2024-000004,329900,captured,1736099388,card,setl_677b1d00
4,pay_0000000005,INV-2025-000001,264900,captured,1736952805,upi,setl_67884c00

Continue H8 - Steps 1 to 6

In [171]:
# Join key: strip spaces and upper-case the RAW reference (the playbook rule).
# The cleaning cell above also rewrites the INV- format, which links ~96% of payments instead of ~77%.
gateway = df_payments_gateway.copy()
raw_ref = pd.read_csv(os.path.join(DATA_DIR, "payments_gateway_export.csv"), usecols=["notes_invoice_ref"])["notes_invoice_ref"]
gateway["ref"] = raw_ref.str.strip().str.upper().values

before = (~raw_ref.isin(df_invoices["invoice_id"])).sum()
after = (~gateway["ref"].isin(df_invoices["invoice_id"])).sum()
print("Payments rescued by the clean:", before - after)      # expect 46,488

Payments rescued by the clean: 46488

In [172]:
# Step 1: invoices in H1 2025 and H1 2026
inv = df_invoices[df_invoices["invoice_date"].dt.month.le(6) & df_invoices["invoice_date"].dt.year.isin([2025, 2026])].copy()
inv["half"] = "H1 " + inv["invoice_date"].dt.year.astype(str)
inv.groupby("half").size()          # expect 157,451 and 162,876

half
H1 2025    157451
H1 2026    162876
dtype: int64

In [173]:
# Steps 3-4: captured payments only, earliest per invoice. The epoch is UTC, so add 5.5 hours for IST.
cap = gateway[gateway["status"] == "captured"].copy()
cap["paid_at"] = pd.to_datetime(cap["created_at_epoch"], unit="s") + pd.Timedelta(hours=5, minutes=30)
cap = cap.sort_values("paid_at").drop_duplicates("ref")

In [174]:
# Step 5: left join - the invoice count must not change
h8 = inv.merge(cap[["ref", "paid_at"]], left_on="invoice_id", right_on="ref", how="left")
print("Invoices in:", len(inv), "| out:", len(h8))

h8["matched"] = h8["paid_at"].notna()
h8["days_to_pay"] = (h8["paid_at"] - h8["invoice_date"]).dt.total_seconds() / 86400

Invoices in: 320327 | out: 320327

In [175]:
# Step 6: matched share and median days to pay
matched = (h8.groupby(["city", "half"])["matched"].mean() * 100).unstack()
print(f'Matched share: 2025 {matched["H1 2025"].min():.1f}-{matched["H1 2025"].max():.1f}%  |  2026 {matched["H1 2026"].min():.1f}-{matched["H1 2026"].max():.1f}%')
print("Median days to pay:"); print(h8.groupby("half")["days_to_pay"].median().round(1))
matched.round(1)

Matched share: 2025 76.7-77.2%  |  2026 74.8-75.6%
Median days to pay:
half
H1 2025    2.1
H1 2026    2.1
Name: days_to_pay, dtype: float64
half       H1 2025  H1 2026
city
Ahmedabad     77.0     75.4
Bengaluru     77.0     75.6
Chennai       77.0     75.6
Hyderabad     77.2     75.5
Jaipur        76.7     74.8
Pune          77.0     74.8

**Verdict H8: rejected.** Median time to pay is 2.1 days in both halves. The matched share fell about 1.5 points, equally in every city, so it cannot explain why only Chennai and Jaipur fell. Payment also comes after booking, so it cannot reduce tests booked. The unmatched share goes to Brief C.

# H9 — Walk-ins

Step 1 and 2: tests by source and year (`source` was added to `h1_data` in H1)

In [176]:
print(h1_data['source'].value_counts())      # exactly three values

src = h1_data.groupby(['source', 'year'])['is_test'].sum().unstack()
src['Growth %'] = ((src['2026'] / src['2025'] - 1) * 100).round(1)
src

source
app       486251
phone     272155
walkin    135898
Name: count, dtype: int64
year      2025    2026  Growth %
source
app     237068  249173       5.1
phone   133050  139098       4.5
walkin   66184   69711       5.3

Step 3: inside Chennai and Jaipur

In [177]:
weak = h1_data[h1_data['city'].isin(['Chennai', 'Jaipur'])]

patients_src = weak.groupby(['city', 'source', 'year'])['patient_id'].nunique().unstack()
patients_src['Patient growth %'] = ((patients_src['2026'] / patients_src['2025'] - 1) * 100).round(1)
patients_src

year             2025   2026  Patient growth %
city    source
Chennai app     11647  11141              -4.3
        phone    8222   7896              -4.0
        walkin   4605   4512              -2.0
Jaipur  app      6800   5858             -13.9
        phone    4267   3881              -9.0
        walkin   2503   2123             -15.2

In [178]:
tests_src = weak.groupby(['city', 'source', 'year'])['is_test'].sum().unstack()
tests_src['Test growth %'] = ((tests_src['2026'] / tests_src['2025'] - 1) * 100).round(1)
tests_src

year             2025   2026  Test growth %
city    source
Chennai app     41617  41980            0.9
        phone   26086  25914           -0.7
        walkin  12564  12864            2.4
Jaipur  app     24819  22112          -10.9
        phone   13436  12238           -8.9
        walkin   6894   5880          -14.7

**Verdict H9: rejected as a cause.** Walk-ins +5.3%, in line with app +5.1% and phone +4.5%. Inside Chennai and Jaipur all three sources fell together (Jaipur patients: app -13.9%, phone -9.0%, walk-in -15.2%). Walk-ins are a symptom of the city loss, not its cause.

# H10 — Test groups

Step 1: tests per visit by year and city (check against H2: 2.2978 and 2.3481)

In [179]:
tv = h1_data.groupby(['city', 'year']).agg(tests=('is_test', 'sum'), visits=('booking_id', 'nunique'))
tv['T/V'] = (tv['tests'] / tv['visits']).round(4)
print('All cities:', (h1_data.groupby('year')['is_test'].sum() / h1_data.groupby('year')['booking_id'].nunique()).round(4).to_dict())
tv['T/V'].unstack()

All cities: {'2025': 2.2978, '2026': 2.3481}
year         2025    2026
city
Ahmedabad  2.3006  2.3439
Bengaluru  2.2882  2.3518
Chennai    2.2958  2.3582
Hyderabad  2.3054  2.3488
Jaipur     2.3009  2.3400
Pune       2.3014  2.3393

Step 2 and 3: packages vs single tests. `tests_catalogue.csv` is not in the uploaded files, so use the playbook rule: PK01 to PK04 are packages. Blank legacy codes count as single tests.

In [180]:
tests_only = h1_data[h1_data['is_test']].copy()
tests_only['is_package'] = tests_only['test_code'].fillna('').str.startswith('PK')
print('Distinct codes:', tests_only['test_code'].nunique())          # 24

groups = tests_only.groupby(['is_package', 'year']).size().unstack()
groups.index = ['Single tests', 'Packages']
groups['Growth %'] = ((groups['2026'] / groups['2025'] - 1) * 100).round(1)
groups

Distinct codes: 24
year            2025    2026  Growth %
Single tests  382190  385069       0.8
Packages       54112   72913      34.7

Step 4: growth by test code, largest fall first

In [181]:
by_code = tests_only.groupby(['test_code', 'year']).size().unstack()
by_code['Growth %'] = ((by_code['2026'] / by_code['2025'] - 1) * 100).round(1)
by_code = by_code.sort_values('Growth %')

singles = by_code[~by_code.index.str.startswith('PK')]
print('Single tests that grew:', (singles['Growth %'] > 0).sum(), 'of', len(singles))      # 16 of 20
by_code.head(5)

Single tests that grew: 16 of 20
year        2025   2026  Growth %
test_code
T015       10457  10156      -2.9
T010       26448  26361      -0.3
T018        3468   3458      -0.3
T007       29656  29597      -0.2
T012        6834   6842       0.1

Step 5: Chennai and Jaipur

In [182]:
weak_tests = tests_only[tests_only['city'].isin(['Chennai', 'Jaipur'])]
g = weak_tests.groupby(['city', 'is_package', 'year']).size().unstack()
g['Growth %'] = ((g['2026'] / g['2025'] - 1) * 100).round(1)
g

year                 2025   2026  Growth %
city    is_package
Chennai False       70307  67937      -3.4
        True         9960  12821      28.7
Jaipur  False       39611  33711     -14.9
        True         5538   6519      17.7

**Verdict H10: rejected.** Tests per visit rose 2.2%. Packages +34.7%, single tests +0.8%, no code fell by more than 2.9% (T015 uric acid). The only single-test falls are in Chennai (-3.4%) and Jaipur (-14.9%), where fewer patients ordered, and packages still grew there.

# H11 — Sample delays and capacity

Step 1 and 2: `visits` and `ops_id` were built in H6. Join collections and keep the collected visits.

In [183]:
collected = visits.merge(df_collections[['booking_id', 'status', 'collected_at']].rename(columns={'booking_id': 'ops_id'}), on='ops_id', how='left')
collected = collected[collected['status'] == 'collected'].copy()
print('Collected visits:', len(collected))

Collected visits: 317179

In [184]:
# A rescheduled visit is collected at the ORIGINAL slot. The originals were dropped earlier, so read their slot from the file.
nova_slots = pd.read_csv(os.path.join(DATA_DIR, "nova.csv"), usecols=["booking_id", "slot_at"]).drop_duplicates("booking_id")
nova_slots["slot_at"] = pd.to_datetime(nova_slots["slot_at"].str[:16], format="%Y-%m-%d %H:%M")
original_slot = collected['ops_id'].map(nova_slots.set_index('booking_id')['slot_at'])

collected['clock_start'] = original_slot.where(collected['rescheduled_from'].notna(), collected['slot_at'])
collected['delay_h'] = (collected['collected_at'] - collected['clock_start']).dt.total_seconds() / 3600

Step 3 and 4: first result per booking, then lab turnaround

In [185]:
df_results = pd.read_csv(os.path.join(DATA_DIR, "results.csv"), low_memory=False)
df_results['result_ts'] = pd.to_datetime(df_results['result_ts'], errors='coerce')

first_result = df_results.groupby('booking_id')['result_ts'].min().rename('first_result')
collected['first_result'] = collected['ops_id'].map(first_result)
collected['tat_h'] = (collected['first_result'] - collected['collected_at']).dt.total_seconds() / 3600

Step 7: sanity check. Negatives are inspected, not dropped.

In [186]:
print('Negative lab turnaround:', (collected['tat_h'] < 0).sum())
early = collected['delay_h'] < 0
print(f'Collected before the slot time: {early.mean():.1%} (the same in both years, so it does not change the comparison)')
print((collected.groupby('year')['delay_h'].apply(lambda s: (s < 0).mean()) * 100).round(1))

Negative lab turnaround: 0
Collected before the slot time: 18.4% (the same in both years, so it does not change the comparison)
year
2025    18.5
2026    18.2
Name: delay_h, dtype: float64

Step 5: median and 90th percentile by city and half

In [187]:
h11 = collected.groupby(['city', 'year']).agg(delay_median=('delay_h', 'median'),
                                              delay_p90=('delay_h', lambda s: s.quantile(0.9)),
                                              tat_median=('tat_h', 'median'),
                                              tat_p90=('tat_h', lambda s: s.quantile(0.9))).round(2)
h11

                delay_median  delay_p90  tat_median  tat_p90
city      year
Ahmedabad 2025          0.57       1.30        11.0     23.0
          2026          0.58       1.30        11.0     23.0
Bengaluru 2025          0.57       1.30        11.0     23.0
          2026          0.58       1.32        11.0     23.0
Chennai   2025          0.58       1.30        11.0     23.0
          2026          0.57       1.32        11.0     23.0
Hyderabad 2025          0.58       1.32        11.0     23.0
          2026          0.57       1.32        11.0     23.0
Jaipur    2025          0.58       1.32        11.0     23.0
          2026          0.58       1.32        11.0     22.0
Pune      2025          0.58       1.30        11.0     23.0
          2026          0.57       1.30        11.0     23.0

Step 6: peak results per day, by city

In [188]:
results_city = df_results.merge(visits[['ops_id', 'city']].drop_duplicates('ops_id'), left_on='booking_id', right_on='ops_id')

results_h1 = results_city[results_city['result_ts'].dt.month.le(6)].copy()
results_h1['year'] = results_h1['result_ts'].dt.year.astype(str)

peak = results_h1.groupby(['city', 'year', results_h1['result_ts'].dt.date]).size().groupby(['city', 'year']).max().unstack()
peak = peak[['2025', '2026']]
peak['Change'] = peak['2026'] - peak['2025']
peak

year       2025  2026  Change
city
Ahmedabad   437   502      65
Bengaluru   542   654     112
Chennai     429   485      56
Hyderabad   418   481      63
Jaipur      283   235     -48
Pune        369   379      10

**Verdict H11: rejected.** Median collection delay 0.57-0.58 h and 90th percentile 1.30-1.32 h in every city and both halves. Median lab turnaround 11 h. Bengaluru's peak day went 542 to 654 results with no slowdown, and Jaipur's lab did less work (283 to 235). There is no sign of a capacity ceiling.

# H12 — Operational blockage

Steps 1 to 3: share of collected visits with no result

In [189]:
collected['has_result'] = collected['ops_id'].isin(df_results['booking_id'])

no_result = (collected.groupby(['city', 'year'])['has_result'].apply(lambda s: (~s).mean() * 100)).unstack()
no_result.round(2)

year       2025  2026
city
Ahmedabad  0.47  0.34
Bengaluru  0.43  0.38
Chennai    0.47  0.42
Hyderabad  0.41  0.40
Jaipur     0.44  0.43
Pune       0.34  0.34

Step 4: lab result rows per 100 booked tests

In [190]:
result_rows = results_city.merge(visits[['ops_id', 'year']].drop_duplicates('ops_id'), on='ops_id')
result_rows = result_rows.groupby(['city', 'year']).size().unstack()

booked = h1_data.groupby(['city', 'year'])['is_test'].sum().unstack()
rows_per_100 = 100 * result_rows / booked
rows_per_100.round(2)

year        2025   2026
city
Ahmedabad  80.91  81.15
Bengaluru  80.62  81.52
Chennai    80.49  81.43
Hyderabad  81.10  81.40
Jaipur     80.85  82.20
Pune       81.03  81.42

In [191]:
print(f"No-result share: 2025 {no_result['2025'].min():.2f}-{no_result['2025'].max():.2f}%  |  2026 {no_result['2026'].min():.2f}-{no_result['2026'].max():.2f}%")
print(f"Result rows per 100 tests: 2025 {rows_per_100['2025'].min():.1f}-{rows_per_100['2025'].max():.1f}  |  2026 {rows_per_100['2026'].min():.1f}-{rows_per_100['2026'].max():.1f}")

No-result share: 2025 0.34-0.47%  |  2026 0.34-0.43%
Result rows per 100 tests: 2025 80.5-81.1  |  2026 81.1-82.2

**Verdict H12: rejected.** Only 0.34-0.47% of collected visits have no result and that share does not rise. Result rows per 100 booked tests moved from 80.5-81.1 to 81.1-82.2. The level is below 100 partly because about 14% of bookings are no-shows (H6) and a result row is a lab run, not a billable test, so read the change, not the level.

# H13 — Payment gateway channels

Step 1: join attempts to invoices for city and half. Unmatched attempts are reported, not dropped.

In [192]:
attempts = gateway.merge(df_invoices[['invoice_id', 'city', 'invoice_date']], left_on='ref', right_on='invoice_id', how='left')
print('Attempts in:', len(gateway), '| out:', len(attempts), '| with no matching invoice:', attempts['city'].isna().sum())

Attempts in: 473507 | out: 473507 | with no matching invoice: 97897

Step 2: half taken from `invoice_date` (same time basis as H8)

In [193]:
attempts = attempts[attempts['invoice_date'].dt.month.le(6) & attempts['invoice_date'].dt.year.isin([2025, 2026])].copy()
attempts['half'] = 'H1 ' + attempts['invoice_date'].dt.year.astype(str)
attempts['failed'] = attempts['status'] == 'failed'
attempts.groupby('half').size()

half
H1 2025    126595
H1 2026    128243
dtype: int64

Step 3: failure rate = failed attempts / all attempts

In [194]:
fail_city = (attempts.groupby(['city', 'half'])['failed'].mean() * 100).unstack()
fail_city.round(2)

half       H1 2025  H1 2026
city
Ahmedabad     3.97     3.86
Bengaluru     3.92     3.81
Chennai       3.78     3.86
Hyderabad     3.73     3.77
Jaipur        3.69     3.58
Pune          3.75     3.82

In [195]:
fail_method = (attempts.groupby(['method', 'half'])['failed'].mean() * 100).unstack()
fail_method.round(2)

half        H1 2025  H1 2026
method
card           3.77     3.82
cash            4.1     3.76
netbanking     3.67     3.74
upi            3.81     3.81

In [196]:
print(f"By city: 2025 {fail_city['H1 2025'].min():.2f}-{fail_city['H1 2025'].max():.2f}%  |  2026 {fail_city['H1 2026'].min():.2f}-{fail_city['H1 2026'].max():.2f}%")
print(f"By method: {fail_method.min().min():.1f}-{fail_method.max().max():.1f}%")

By city: 2025 3.69-3.97%  |  2026 3.58-3.86%
By method: 3.7-4.1%

**Verdict H13: rejected.** Failure rates sit in a narrow band for every city (3.58-3.97%) and method (3.7-4.1%) and edged down in 2026. Chennai and Jaipur do not stand out. Settlement and reconciliation belong to Brief C.

# H14 — Marketing campaigns and budgets

Step 1: check `campaigns.csv` has one row per booking

In [197]:
df_campaigns = pd.read_csv(os.path.join(DATA_DIR, "campaigns.csv"))
print('One row per booking_id:', df_campaigns['booking_id'].is_unique)
print(df_campaigns['campaign_id'].value_counts().to_dict(), '| waiver_rs:', df_campaigns['waiver_rs'].unique())

One row per booking_id: True
{'HC-FREE-2026Q1': 48869} | waiver_rs: [150]

Step 2: tag each visit (`visits` from H6) and label new vs returning patients

In [198]:
v14 = visits.merge(df_patients[['patient_id', 'signup_date']], on='patient_id', how='left')
v14['ptype'] = np.where(v14['signup_date'].dt.year >= v14['year'].astype(int), 'new', 'returning')
v14['is_tagged'] = v14['booking_id'].isin(df_campaigns['booking_id'])

print('Visits:', len(v14), '| tagged:', v14['is_tagged'].sum())                                    # 46,871
print('Campaign rows with no eligible visit:', (~df_campaigns['booking_id'].isin(v14['booking_id'])).sum())

Visits: 384921 | tagged: 46871
Campaign rows with no eligible visit: 1998

Step 3: describe the tagged visits

In [199]:
tagged = v14[v14['is_tagged']]
print('Channel:', tagged['channel'].value_counts().to_dict())
print('Year:', tagged['year'].unique().tolist(), '| months:', sorted(tagged['slot_at'].dt.month.unique().tolist()))

Channel: {'home': 46871}
Year: ['2026'] | months: [1, 2, 3]

Step 4: uptake by city = tagged visits / all 2026 visits in the city

In [200]:
v26 = v14[v14['year'] == '2026']
uptake = (v26.groupby('city')['is_tagged'].mean() * 100).round(1)
print(f'Range: {uptake.min()}-{uptake.max()}%')                                              # 23.6-24.6
uptake

Range: 23.6-24.6%
city
Ahmedabad    23.6
Bengaluru    24.0
Chennai      24.0
Hyderabad    24.1
Jaipur       24.1
Pune         24.6
Name: is_tagged, dtype: float64

Step 5: share of new patients, tagged visits vs all Q1 2026 visits

In [201]:
q1_2026 = v26[v26['slot_at'].dt.month <= 3]
print(f"New share of tagged visits: {(tagged['ptype'] == 'new').mean() * 100:.1f}%")            # 28.8
print(f"New share of all Q1 2026 visits: {(q1_2026['ptype'] == 'new').mean() * 100:.1f}%")       # 28.9

New share of tagged visits: 28.8%
New share of all Q1 2026 visits: 28.9%

Step 6: home share of tests by month (from H3)

In [202]:
home_share

year   2025  2026
month
1      34.3  49.4
2      33.9  49.1
3      34.4  48.9
4      34.4  40.1
5      34.0  40.1
6      34.2  40.2

**Verdict H14: rejected as the cause of the shortfall; budget is out of scope.** For the campaign to explain the shortfall it would have to differ between cities, but uptake is 23.6-24.6% everywhere. It moved existing patients from clinic to home without pulling in new patients disproportionately. In the weak cities it cushioned the loss (new home patients fell less than new clinic patients, H7c).

**Out of scope:** whether the campaign added net volume or was worth its cost is Brief E. The data holds only the Rs 150 waiver per visit, no budgets, so no ROI is claimed.

# Convergence for H8-H14
| # | Hypothesis | Status | Deciding evidence |
|---|---|---|---|
| H8 | Payment delays | Contradicted; outside the tree | Median 2.1 days both halves |
| H9 | Walk-ins | Contradicted | Walk-ins +5.3%, in line with other sources |
| H10 | Test groups | Contradicted | T/V +2.2%; packages +34.7% |
| H11 | Capacity | Contradicted | Delay and turnaround flat; peaks absorbed |
| H12 | Blockage | Contradicted | No-result share 0.34-0.47%, flat |
| H13 | Gateway channels | Contradicted; outside the tree | Failure rates 3.6-4.1%, flat |
| H14 | Campaigns | Contradicted as cause; budget out of scope | Uptake 23.6-24.6% in every city |